// The clearance file is produced, not typed.
//
// Every number in src/components/chat/clearance/ is a measurement of one body
// under the ten clips, and the two producers (scripts/measure-motions.ts
// --write, scripts/avatar/springsim.ts --clearance) are the only way a number
// gets in. What this holds is the wiring: the real entry point, run as a
// subprocess, writes a module whose rig identity is the body's own, and the
// combiner refuses to pair measurements that were not taken on the same rig.
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

import {
  combineClearance,
  crownBound,
  crownOn,
  type ClearanceDecisions,
  type ClearanceMeasured,
  type ClearanceSimulated,
} from './clearance'
import { CLEARANCE } from './clearance/vroid-sample-b'
import { parseGlb, rigOf } from './vrmHumanoid'

const BODY = path.join('public', 'avatar', 'AvatarSample_B_webp.vrm')

const sha256 = (s: string): string => createHash('sha256').update(s).digest('hex')

/**
 * The shipped body with its scene roots scaled, written beside the test's
 * output: a body whose rig is NOT the family's, so a producer that wrote the
 * family's sha instead of reading the body's would be caught. (The same
 * construction as measure-motions.test.ts's taller body.)
 */
function otherRig(dir: string, factor: number): { file: string; json: ReturnType<typeof parseGlb>['json'] } {
  const raw = readFileSync(BODY)
  const view = new DataView(raw.buffer, raw.byteOffset, raw.byteLength)
  const jsonLength = view.getUint32(12, true)
  const doc = JSON.parse(new TextDecoder().decode(raw.subarray(20, 20 + jsonLength))) as ReturnType<typeof parseGlb>['json']
  for (const index of doc.scenes?.[doc.scene ?? 0]?.nodes ?? []) {
    const node = doc.nodes[index]
    node.scale = (node.scale ?? [1, 1, 1]).map((v) => v * factor)
  }
  let blob = new TextEncoder().encode(JSON.stringify(doc))
  const pad = (4 - (blob.length % 4)) % 4
  if (pad) {
    const padded = new Uint8Array(blob.length + pad)
    padded.set(blob)
    padded.fill(0x20, blob.length)
    blob = padded
  }
  const rest = raw.subarray(20 + jsonLength)
  const out = new Uint8Array(20 + blob.length + rest.length)
  const dv = new DataView(out.buffer)
  dv.setUint32(0, 0x46546c67, true)
  dv.setUint32(4, 2, true)
  dv.setUint32(8, out.length, true)
  dv.setUint32(12, blob.length, true)
  dv.setUint32(16, view.getUint32(16, true), true)
  out.set(blob, 20)
  out.set(rest, 20 + blob.length)
  const file = path.join(dir, `taller-${factor}.vrm`)
  writeFileSync(file, out)
  return { file, json: doc }
}

describe('clearance producers', () => {
  it('measure-motions --write records the rig it measured', async () => {
    const dir = mkdtempSync(path.join(tmpdir(), 'clearance-'))
    const body = otherRig(dir, 1.1)
    const out = path.join(dir, 'probe.measured.gen.ts')
    execFileSync('npx', ['tsx', 'scripts/measure-motions.ts', body.file, '--write', out, '--family=probe'], {
      cwd: process.cwd(),
      stdio: 'pipe',
    })
    // The module is one `export const MEASURED: ClearanceMeasured = {...}`
    // whose literal is JSON; read as such, because vite will not import a
    // module from outside the project root and the committed copies are
    // already imported by every consumer.
    const text = readFileSync(out, 'utf8')
    expect(text).toMatch(/^\/\/ GENERATED by scripts\/measure-motions\.ts --write/)
    expect(text).toContain('export const MEASURED: ClearanceMeasured = {')
    const MEASURED = JSON.parse(text.slice(text.indexOf('= {') + 2)) as ClearanceMeasured
    expect(MEASURED.family).toBe('probe')
    // This body's own rig, which is not the family's.
    expect(MEASURED.rigSha).toBe(sha256(rigOf(body.json)))
    expect(MEASURED.rigSha).not.toBe(CLEARANCE.rigSha)
    // Outside public/, the path is recorded as given.
    expect(MEASURED.measuredOn).toBe(body.file)
    // Every clip the pool declares, with the sweep's own numbers on it: 10%
    // taller, the resting crown and the face box scale with it.
    expect(Object.keys(MEASURED.clips).sort()).toEqual(Object.keys(CLEARANCE.clips).sort())
    expect(MEASURED.restCrownY).toBeCloseTo(CLEARANCE.clips.dance ? 1.582 * 1.1 : 0, 2)
    expect(MEASURED.faceBox.max[1]).toBeCloseTo(1.5034 * 1.1, 2)
    // The ratio is scale-free (the box scales with the body), so a 10% taller
    // copy reads what the shipped one does.
    expect(MEASURED.clips.dance.faceRatio).toBeGreaterThan(0.19)
    expect(MEASURED.clips.dance.faceRatio).toBeLessThan(0.21)
    expect(MEASURED.handSkinPastTip).toBeGreaterThan(0.012)
  }, 120_000)
})

describe('combineClearance', () => {
  const measured: ClearanceMeasured = {
    family: 'f',
    rigSha: 'abc',
    measuredOn: '/avatar/a.vrm',
    producedBy: 'deadbeef',
    faceBox: { min: [-0.1, 1.2, -0.1], max: [0.1, 1.5, 0.05] },
    handSkinPastTip: 0.018,
    restCrownY: 1.582,
    clips: {
      dance: {
        reach: { left: 0.5, right: 0.3 },
        skinTop: 1.4,
        hipsLow: 0.75,
        faceRatio: 0.3,
        faceRatioAt: 8.2,
        endSink: 0.02,
        hipsDrift: 0.14,
        endWrist: 1.19,
      },
    },
  }
  const simulated: ClearanceSimulated = {
    family: 'f',
    rigSha: 'abc',
    simulatedOn: '/avatar/b.vrm',
    producedBy: 'deadbeef',
    restCrownY: 1.5757,
    restCrownScreen: { waistUp: 1.578, column: 1.588 },
    framings: { fov: 27, tilt: 0.1, frames: { waistUp: { distance: 2.3, lookAtY: 1.32 }, column: { distance: 2.441, lookAtY: 1.016 } }, pans: {} },
    clips: {
      dance: {
        crownY: 1.6647,
        crownT: 11.97,
        crownScreen: { waistUp: 1.7013, column: 1.7099 },
        coatDepthMm: 38,
        bodyDepthMm: 50,
        jumpDeg: 21.7,
        skirtDepthMm: 18,
      },
    },
  }
  const decisions: ClearanceDecisions = {
    crownFringe: 0.01,
    crownFringeMeasured: '2026-09-06 column, alpha > 8',
    crownSeen: {},
    waivers: {},
    excluded: {},
  }

  it('pairs two producers only on the same rig', () => {
    const file = combineClearance(measured, simulated, decisions)
    expect(file.clips.dance.crownY).toBe(1.6647)
    expect(file.clips.dance.faceRatio).toBe(0.3)
    expect(() => combineClearance(measured, { ...simulated, rigSha: 'xyz' }, decisions)).toThrow(/rig/)
    expect(() => combineClearance(measured, { ...simulated, family: 'g' }, decisions)).toThrow(/family/)
    expect(() => combineClearance(measured, { ...simulated, clips: {} }, decisions)).toThrow(/dance/)
  })

  it('refuses a missing browser fringe rather than defaulting it', () => {
    // The fringe is the one number no script produces. Absent, the crown row
    // would silently compare the projected vertex against the frame with no
    // record of whether anyone ever checked it against a drawn pixel.
    const bad = { ...decisions, crownFringe: Number.NaN }
    expect(() => combineClearance(measured, simulated, bad)).toThrow(/crownFringe/)
  })

  it('transfers a clip crown onto another body by its own resting crown', () => {
    const file = combineClearance(measured, simulated, decisions)
    // the frame's projected crown, moved by the two bodies' rest crowns, plus the fringe
    expect(crownOn(file, 'dance', 'column', 1.6)).toBeCloseTo(1.7099 - 1.5757 + 1.6 + 0.01, 6)
    expect(crownOn(file, 'dance', 'waistUp', 1.6)).toBeCloseTo(1.7013 - 1.5757 + 1.6 + 0.01, 6)
    // a browser sweep that drew it higher wins, per frame
    const seen = combineClearance(measured, simulated, { ...decisions, crownSeen: { dance: { column: 1.9 } } })
    expect(crownBound(seen, 'dance', 'column', 1.6)).toBe(1.9)
    expect(crownBound(seen, 'dance', 'waistUp', 1.6)).toBeCloseTo(crownOn(seen, 'dance', 'waistUp', 1.6), 9)
  })
})
