// The clearance file is produced, not typed.
//
// Every number in src/components/chat/clearance/ is a measurement of one body
// under the ten clips, and the two producers (scripts/measure-motions.ts
// --write, scripts/avatar/springsim.ts --clearance) are the only way a number
// gets in. What this holds is the wiring: the real entry point, run as a
// subprocess, writes a module whose rig identity is the body's own, and the
// combiner refuses to pair measurements that were not taken on the same rig.
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

import {
  combineClearance,
  crownBound,
  crownOn,
  panFor,
  panRange,
  type ClearanceDecisions,
  type ClearanceMeasured,
  type ClearanceSimulated,
} from './clearance'
import { CLEARANCE } from './clearance/vroid-sample-b'
import { SIMULATED as PINK_SIMULATED } from './clearance/vroid-sample-b.pink.simulated.gen'
import { AVATAR_MOTIONS } from './avatarMotions'
import { avatarViewSpan, stepFramePan } from './avatarMode'
import type { MotionFrame } from './avatarMotions'
import { parseGlb, readAccessorRows, rigOf, type GltfJson } from './vrmHumanoid'
import { AVATAR_VARIANTS } from './avatarVariants'

const BODY = path.join('public', 'avatar', 'AvatarSample_B_webp.vrm')

const sha256 = (s: string): string => createHash('sha256').update(s).digest('hex')

/**
 * The shipped body with its scene roots scaled, written beside the test's
 * output: a body whose rig is NOT the family's, so a producer that wrote the
 * family's sha instead of reading the body's would be caught. (The same
 * construction as measure-motions.test.ts's taller body.)
 */
function otherRig(dir: string, factor: number): { file: string; json: ReturnType<typeof parseGlb>['json'] } {
  const raw = readFileSync(BODY)
  const view = new DataView(raw.buffer, raw.byteOffset, raw.byteLength)
  const jsonLength = view.getUint32(12, true)
  const doc = JSON.parse(new TextDecoder().decode(raw.subarray(20, 20 + jsonLength))) as ReturnType<typeof parseGlb>['json']
  for (const index of doc.scenes?.[doc.scene ?? 0]?.nodes ?? []) {
    const node = doc.nodes[index]
    node.scale = (node.scale ?? [1, 1, 1]).map((v) => v * factor)
  }
  let blob = new TextEncoder().encode(JSON.stringify(doc))
  const pad = (4 - (blob.length % 4)) % 4
  if (pad) {
    const padded = new Uint8Array(blob.length + pad)
    padded.set(blob)
    padded.fill(0x20, blob.length)
    blob = padded
  }
  const rest = raw.subarray(20 + jsonLength)
  const out = new Uint8Array(20 + blob.length + rest.length)
  const dv = new DataView(out.buffer)
  dv.setUint32(0, 0x46546c67, true)
  dv.setUint32(4, 2, true)
  dv.setUint32(8, out.length, true)
  dv.setUint32(12, blob.length, true)
  dv.setUint32(16, view.getUint32(16, true), true)
  out.set(blob, 20)
  out.set(rest, 20 + blob.length)
  const file = path.join(dir, `taller-${factor}.vrm`)
  writeFileSync(file, out)
  return { file, json: doc }
}

describe('clearance producers', () => {
  it('measure-motions --write records the rig it measured', async () => {
    const dir = mkdtempSync(path.join(tmpdir(), 'clearance-'))
    const body = otherRig(dir, 1.1)
    const out = path.join(dir, 'probe.measured.gen.ts')
    execFileSync('npx', ['tsx', 'scripts/measure-motions.ts', body.file, '--write', out, '--family=probe'], {
      cwd: process.cwd(),
      stdio: 'pipe',
    })
    // The module is one `export const MEASURED: ClearanceMeasured = {...}`
    // whose literal is JSON; read as such, because vite will not import a
    // module from outside the project root and the committed copies are
    // already imported by every consumer.
    const text = readFileSync(out, 'utf8')
    expect(text).toMatch(/^\/\/ GENERATED by scripts\/measure-motions\.ts --write/)
    expect(text).toContain('export const MEASURED: ClearanceMeasured = {')
    const MEASURED = JSON.parse(text.slice(text.indexOf('= {') + 2)) as ClearanceMeasured
    expect(MEASURED.family).toBe('probe')
    // This body's own rig, which is not the family's.
    expect(MEASURED.rigSha).toBe(sha256(rigOf(body.json)))
    expect(MEASURED.rigSha).not.toBe(CLEARANCE.rigSha)
    // Outside public/, the path is recorded as given.
    expect(MEASURED.measuredOn).toBe(body.file)
    // Every clip the pool declares, with the sweep's own numbers on it: 10%
    // taller, the resting crown and the face box scale with it.
    expect(Object.keys(MEASURED.clips).sort()).toEqual(Object.keys(CLEARANCE.clips).sort())
    expect(MEASURED.restCrownY).toBeCloseTo(CLEARANCE.clips.dance ? 1.582 * 1.1 : 0, 2)
    expect(MEASURED.faceBox.max[1]).toBeCloseTo(1.5034 * 1.1, 2)
    // The ratio is scale-free (the box scales with the body), so a 10% taller
    // copy reads what the shipped one does.
    expect(MEASURED.clips.dance.faceRatio).toBeGreaterThan(0.19)
    expect(MEASURED.clips.dance.faceRatio).toBeLessThan(0.21)
    expect(MEASURED.handSkinPastTip).toBeGreaterThan(0.012)
  }, 120_000)
})

describe('every body of the family, not only the one that was simulated', () => {
  // The crown a clip has to clear is a property of the BODY, not of the rig:
  // three bodies share this family and their hair differs. Until 2026-09-07
  // only one of them could be simulated (springsim refused a body with no
  // .parts.json), so the other two got a crown transferred onto them by
  // crownOn -- the simulated body's crown motion re-anchored on their own
  // resting crown -- with crownSeen carrying four hand-swept corrections where
  // that under-read.
  //
  // deriveManifest lifted the restriction, so pink now has a crown of its own,
  // and the transfer turns out to be wrong in both directions: it over-reads
  // idleLoop's column by 39.4mm and under-reads playFingers' waist-up by
  // 30.7mm. What matters is the under-reads, because the pan every body shares
  // was solved against the bound (avatarGuideEngine passes no body to
  // motionPan).
  const FRINGE = CLEARANCE.crownFringe
  // The body the guards are evaluated on, and the worst of the family: the
  // transfer only means anything when it is anchored on a real body's resting
  // crown, and reading the file's own 1.5757 back into crownOn cancels it and
  // measures the simulated body against itself. rigProbe.test.ts uses
  // deriveRestCrown(AvatarSample_B); PINK_SIMULATED.restCrownY is that number,
  // taken from the file rather than re-derived here.
  const REST_CROWN = PINK_SIMULATED.restCrownY

  it('is one simulation because the two VRoid bodies are one geometry', () => {
    // pink's ten clips stand in for the base sample's as well, and that is only
    // sound while the two files are the same mesh: one is a recolour of the
    // other, so their textures differ and not a vertex does. Simulating both
    // took 95 minutes to produce two files differing in nothing but the body's
    // name, which is the check that should have been run FIRST.
    //
    // If they ever diverge -- a re-export, a hair edit on one of them -- this
    // reddens, because from that moment the base body has a crown nobody has
    // measured and the family's worst is missing a candidate.
    const geometry = (url: string): string => {
      const raw = readFileSync(path.join(process.cwd(), 'public', url.replace(/^\//, '')))
      const glb = parseGlb<GltfJson>(new Uint8Array(raw))
      const digest = createHash('sha256')
      for (const mesh of glb.json.meshes ?? []) {
        for (const prim of mesh.primitives) {
          // Sorted so two files that list the same attributes in another order
          // still hash alike; the textures live elsewhere and are meant to differ.
          for (const key of Object.keys(prim.attributes).sort()) {
            const rows = readAccessorRows(glb as Parameters<typeof readAccessorRows>[0], prim.attributes[key])
            digest.update(key)
            digest.update(new Uint8Array(rows.data.buffer, rows.data.byteOffset, rows.data.byteLength))
          }
        }
      }
      return digest.digest('hex').slice(0, 16)
    }
    const pink = AVATAR_VARIANTS.find((v) => v.id === 'pink')
    const base = AVATAR_VARIANTS.find((v) => v.id === 'base')
    expect(pink && base, 'both VRoid variants are declared').toBeTruthy()
    expect(geometry(base!.url), `${base!.url} is no longer the same mesh as ${pink!.url}`)
      .toBe(geometry(pink!.url))
    expect(PINK_SIMULATED.simulatedOn, 'and pink is the one that was simulated').toBe(pink!.url)
  })

  const ceilingOf = (clip: string, frame: MotionFrame): number => {
    const span = avatarViewSpan(CLEARANCE.framings.frames[frame], CLEARANCE.framings.fov)
    const pan = CLEARANCE.pans[clip]?.[frame] ?? 0
    // The waiver raises the edge and never lowers it: every one of them was
    // decided on the column framing, and replacing the edge outright put
    // spin's 1.6200 concession 252mm below the waist-up frame (clearance.ts
    // panRange).
    return Math.max(span.top, CLEARANCE.clips[clip].waiver?.crownTop ?? -Infinity) + pan
  }

  it('carries every simulated body into the crown it hands out', () => {
    // The wiring, not the arithmetic. Reading the pink file directly and
    // comparing it to a ceiling was the first version of this test, and it
    // passed with that body left out of combineClearance entirely -- it never
    // asked the clearance file anything (evidence/mutations-0907-crown.md K3,
    // the shape feedback_injection_bypasses_wiring is about). What has to hold
    // is that the bound the FILE hands out is at least what each body it names
    // actually draws.
    const missed: string[] = []
    for (const [clip, def] of Object.entries(AVATAR_MOTIONS)) {
      for (const frame of def.placements) {
        const bound = crownBound(CLEARANCE, clip, frame, REST_CROWN)
        for (const body of CLEARANCE.alsoSimulated) {
          const drawn = body.clips[clip].crownScreen[frame] + FRINGE
          if (bound + 1e-9 < drawn) {
            missed.push(`${clip}/${frame}: ${body.simulatedOn} draws ${drawn.toFixed(4)}, the file bounds ${bound.toFixed(4)}`)
          }
        }
      }
    }
    expect(CLEARANCE.alsoSimulated.length, 'a second body was simulated at all').toBeGreaterThan(0)
    expect(missed, 'the family hands out a crown lower than one of its own bodies draws').toEqual([])
  })

  it('has the pan it needs by the time the crown gets there, not only at rest', () => {
    // A pan is not applied the moment a clip starts: stepFramePan eases the
    // camera onto it, and rigProbe.test's crown guard compares against the
    // SETTLED edge. That was harmless while the only panning clip was `dance`,
    // whose crown peaks at 11.97s with the camera long since parked. The two
    // clips that took a +0.02 column pan on 2026-09-07 are not like that:
    // pink's scratchHead throws its crown at t=1.10s, with 83% of 2cm applied.
    //
    // Still clears, by 4.4mm rather than the 7.8mm the settled guard derives.
    // What this pins is that a future pan on an early-peaking clip cannot be
    // derived against a camera that has not arrived yet.
    const DT = 1 / 60
    const applied = (target: number, t: number): number => {
      let v = 0
      for (let elapsed = 0; elapsed < t; elapsed += DT) v = stepFramePan(v, target, DT)
      return v
    }
    const late: string[] = []
    for (const [clip, def] of Object.entries(AVATAR_MOTIONS)) {
      for (const frame of def.placements) {
        const pan = CLEARANCE.pans[clip]?.[frame] ?? 0
        if (pan <= 0) continue // a downward pan buys headroom at the top from the first frame
        const settled = ceilingOf(clip, frame)
        // Every body that contributes a crown, each at ITS OWN peak time: the
        // file's clip carries the simulated body's crownT, and each
        // alsoSimulated body carries its own.
        const peaks: [number, number, string][] = [
          [CLEARANCE.clips[clip].crownT, crownOn(CLEARANCE, clip, frame, REST_CROWN), CLEARANCE.simulatedOn],
          ...CLEARANCE.alsoSimulated.map((b): [number, number, string] =>
            [b.clips[clip].crownT, b.clips[clip].crownScreen[frame] + FRINGE, b.simulatedOn]),
        ]
        for (const [t, crown, body] of peaks) {
          const edge = settled - pan + applied(pan, t)
          if (crown > edge) {
            late.push(`${clip}/${frame}: ${body} draws ${crown.toFixed(4)} at t=${t}s, edge only ${edge.toFixed(4)} by then`)
          }
        }
      }
    }
    expect(late, 'a clip reaches its crown before the pan that clears it does').toEqual([])
  })

  it('keeps every declared body inside the frame it is filmed in', () => {
    const over: string[] = []
    for (const [clip, def] of Object.entries(AVATAR_MOTIONS)) {
      for (const frame of def.placements) {
        const bound = crownBound(CLEARANCE, clip, frame, REST_CROWN)
        const ceiling = ceilingOf(clip, frame)
        if (bound > ceiling) {
          over.push(`${clip}/${frame} by ${((bound - ceiling) * 1000).toFixed(1)}mm`)
        }
      }
    }
    expect(over, 'a body of this family draws its crown above the top of frame').toEqual([])
  })
})

describe('combineClearance', () => {
  const measured: ClearanceMeasured = {
    family: 'f',
    rigSha: 'abc',
    measuredOn: '/avatar/a.vrm',
    producedBy: 'deadbeef',
    faceBox: { min: [-0.1, 1.2, -0.1], max: [0.1, 1.5, 0.05] },
    handSkinPastTip: 0.018,
    restCrownY: 1.582,
    clips: {
      dance: {
        reach: { left: 0.5, right: 0.3 },
        skinTop: 1.4,
        hipsLow: 0.75,
        faceRatio: 0.3,
        faceRatioAt: 8.2,
        endSink: 0.02,
        hipsDrift: 0.14,
        endWrist: 1.19,
      },
    },
  }
  const simulated: ClearanceSimulated = {
    family: 'f',
    rigSha: 'abc',
    simulatedOn: '/avatar/b.vrm',
    producedBy: 'deadbeef',
    restCrownY: 1.5757,
    restCrownScreen: { waistUp: 1.578, column: 1.588 },
    framings: { fov: 27, tilt: 0.1, frames: { waistUp: { distance: 2.3, lookAtY: 1.32 }, column: { distance: 2.441, lookAtY: 1.016 } }, pans: {} },
    clips: {
      dance: {
        crownY: 1.6647,
        crownT: 11.97,
        crownScreen: { waistUp: 1.7013, column: 1.7099 },
        coatDepthMm: 38,
        bodyDepthMm: 50,
        jumpDeg: 21.7,
        skirtDepthMm: 18,
      },
    },
  }
  const decisions: ClearanceDecisions = {
    crownFringe: 0.01,
    crownFringeMeasured: '2026-09-06 column, alpha > 8',
    crownSeen: {},
    pans: {},
    waivers: {},
    excluded: {},
  }

  it('pairs two producers only on the same rig', () => {
    const file = combineClearance(measured, simulated, decisions)
    expect(file.clips.dance.crownY).toBe(1.6647)
    expect(file.clips.dance.faceRatio).toBe(0.3)
    expect(() => combineClearance(measured, { ...simulated, rigSha: 'xyz' }, decisions)).toThrow(/rig/)
    expect(() => combineClearance(measured, { ...simulated, family: 'g' }, decisions)).toThrow(/family/)
    expect(() => combineClearance(measured, { ...simulated, clips: {} }, decisions)).toThrow(/dance/)
  })

  it('refuses a decision naming a clip no producer measured, whichever kind of decision it is', () => {
    // Three fields name clips, and a name outside the pool is a setting nothing
    // will ever read: the clip was renamed or dropped and the decision stayed.
    // `pans` is the one this check forgot when pans moved off AvatarMotionDef on
    // 2026-09-07, and it is the kind that hides best -- a wrong pan VALUE is
    // recomputed by rigProbe.test.ts against panFor, but a pan for a clip that
    // is not in the pool is looked up by name and so never looked up at all.
    expect(() => combineClearance(measured, simulated, { ...decisions, waivers: { squat: { hipsDrift: 0.2 } } })).toThrow(/squat/)
    expect(() => combineClearance(measured, simulated, { ...decisions, crownSeen: { squat: { column: 1.6 } } })).toThrow(/squat/)
    expect(() => combineClearance(measured, simulated, { ...decisions, pans: { squat: { column: 0.02 } } })).toThrow(/squat/)
  })

  it('refuses a second body simulated under another composition', () => {
    // crownScreen is a projection through the frame's camera WITH the clip's
    // pan applied, so a body simulated under an older framing, lens or pan is
    // carrying numbers for a shot the site no longer takes. The guard that
    // catches this for the primary simulation (rigProbe.test.ts, "was
    // simulated under the composition the engine uses today") reads
    // ClearanceFile.framings, and combineClearance fills that from the primary
    // alone -- so a stale second body would have reached crownBound with
    // nothing looking at it.
    const twin = { ...simulated, simulatedOn: '/avatar/c.vrm' }
    expect(combineClearance(measured, simulated, decisions, [twin]).alsoSimulated).toHaveLength(1)
    const otherLens = { ...twin, framings: { ...twin.framings, fov: 13.5 } }
    expect(() => combineClearance(measured, simulated, decisions, [otherLens]))
      .toThrow(/composition/)
    const otherPan = { ...twin, framings: { ...twin.framings, pans: { dance: { column: 0.13 } } } }
    expect(() => combineClearance(measured, simulated, decisions, [otherPan]))
      .toThrow(/composition/)
    const otherFrame = {
      ...twin,
      framings: {
        ...twin.framings,
        frames: { ...twin.framings.frames, column: { distance: 2.441, lookAtY: 1.1 } },
      },
    }
    expect(() => combineClearance(measured, simulated, decisions, [otherFrame]))
      .toThrow(/composition/)
  })

  it('refuses a missing browser fringe rather than defaulting it', () => {
    // The fringe is the one number no script produces. Absent, the crown row
    // would silently compare the projected vertex against the frame with no
    // record of whether anyone ever checked it against a drawn pixel.
    const bad = { ...decisions, crownFringe: Number.NaN }
    expect(() => combineClearance(measured, simulated, bad)).toThrow(/crownFringe/)
  })

  it('measures the pan against the fov the file was produced under', () => {
    // The distance and lookAtY come from the file already; the half-span used
    // to come from the site's current AVATAR_FOV, so a file produced under a
    // different lens would have been read through today's. Halving the fov
    // narrows the span and moves the range, and nothing else here changes.
    const file = combineClearance(measured, simulated, decisions)
    const narrow = combineClearance(measured,
      { ...simulated, framings: { ...simulated.framings, fov: 13.5 } }, decisions)
    const wide = panRange(file, 'dance', 'column', file.restCrownY, ['column'])
    const tight = panRange(narrow, 'dance', 'column', narrow.restCrownY, ['column'])
    expect(tight.least).toBeGreaterThan(wide.least)
    expect(tight.most).toBeLessThan(wide.most)
  })

  it('refuses a pan that its own rounding puts outside the range', () => {
    // The range can be narrower than the centimetre these are dialled in. On
    // today's data the narrowest is 70mm against a 10mm step, so this is a
    // synthetic body: hips that leave the bottom edge 1mm after the crown comes
    // inside the top. Rounding up then lands past `most`, and returning it
    // quietly would put a composition nobody measured into the frame.
    // The column spans 0.430..1.602. A crown at 1.606 needs 4mm of lift; hips
    // at 0.439 allow 9mm before they leave. 4mm rounds up to a whole
    // centimetre, which is 1mm too far.
    const pinched = combineClearance(
      { ...measured, clips: { dance: { ...measured.clips.dance, hipsLow: 0.439 } } },
      { ...simulated, clips: { dance: { ...simulated.clips.dance, crownScreen: { waistUp: 1.5, column: 1.5 } } } },
      { ...decisions, crownSeen: { dance: { column: 1.606 } } },
    )
    const r = panRange(pinched, 'dance', 'column', pinched.restCrownY, ['column'])
    expect(r.most - r.least, 'a range narrower than the rounding step').toBeLessThan(0.01)
    expect(r.least, 'and one that does not contain zero').toBeGreaterThan(0)
    expect(() => panFor(pinched, 'dance', 'column', pinched.restCrownY, 'least', ['column']))
      .toThrow(/no pan on the centimetre/)
  })

  it('lets a waiver raise a frame edge and never lower one', () => {
    // Every crownTop waiver on the shipped family was decided on the column
    // framing, whose top edge is 1.6020; the waist-up frame's is 1.8722. Until
    // 2026-09-07 the waiver REPLACED the edge, so a 1.606 concession became a
    // ceiling 266mm below the frame the clip is actually filmed in, and a clip
    // clearing that frame by a quarter of a metre read as 16mm over the top.
    //
    // The shipped file cannot show this any more: the two clips it bit are the
    // two whose waivers a pan replaced. So it is shown here, on a file built to
    // have exactly that shape -- a waiver far under the waist-up edge.
    const file = combineClearance(measured, simulated, {
      ...decisions,
      waivers: { dance: { crownTop: 1.61 } },
    })
    const wide = avatarViewSpan(file.framings.frames.waistUp, file.framings.fov)
    expect(wide.top, 'the waist-up edge sits well above the waiver').toBeGreaterThan(1.61)
    const range = panRange(file, 'dance', 'waistUp', file.restCrownY, ['waistUp'])
    const crown = crownBound(file, 'dance', 'waistUp', file.restCrownY)
    // The clip is inside the frame, so it needs no upward pan at all. Measured
    // against the waiver instead, it would ask for one it does not need.
    expect(crown).toBeLessThan(wide.top)
    expect(range.least).toBeCloseTo(crown - wide.top, 9)
    expect(range.least).toBeLessThan(0)
  })

  it('transfers a clip crown onto another body by its own resting crown', () => {
    const file = combineClearance(measured, simulated, decisions)
    // the frame's projected crown, moved by the two bodies' rest crowns, plus the fringe
    expect(crownOn(file, 'dance', 'column', 1.6)).toBeCloseTo(1.7099 - 1.5757 + 1.6 + 0.01, 6)
    expect(crownOn(file, 'dance', 'waistUp', 1.6)).toBeCloseTo(1.7013 - 1.5757 + 1.6 + 0.01, 6)
    // a browser sweep that drew it higher wins, per frame
    const seen = combineClearance(measured, simulated, { ...decisions, crownSeen: { dance: { column: 1.9 } } })
    expect(crownBound(seen, 'dance', 'column', 1.6)).toBe(1.9)
    expect(crownBound(seen, 'dance', 'waistUp', 1.6)).toBeCloseTo(crownOn(seen, 'dance', 'waistUp', 1.6), 9)
  })
})
