// GENERATED by scripts/derive-coat-swing.ts --write in the vtuber-kit repo: do not edit by hand.
// Degrees each upper arm turns out from her side, every COAT_SWING_STEP seconds of the clip (coatSwing.ts).
export const COAT_SWING_CURVES: Record<string, Record<string, readonly number[]>> = {
  '/avatar/mika-milfy-13.vrm': {
    catwalk: [32.5, 32.5, 32.5, 30, 27.5, 17.5, 17.5, 17.5, 17.5, 17.5, 15, 15, 15, 15, 10, 15, 15, 15, 15, 20, 30, 35, 35, 35, 35, 35, 35, 32.5, 32.5, 32.5, 32.5, 32.5, 30, 25, 17.5, 17.5, 15, 15, 12.5, 12.5, 12.5, 12.5, 12.5, 10, 12.5, 12.5, 17.5, 17.5, 17.5, 17.5, 17.5, 17.5, 17.5, 12.5, 22.5, 27.5, 32.5, 32.5, 32.5, 32.5, 32.5],
  },
}
