// The producer side of src/components/chat/clearance.ts: how a script names
// the rig it read and writes a generated module the app can import.
import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import { rigOf, type GltfJson } from '../../src/components/chat/vrmHumanoid'

/** The rig's identity: sha256 of vrmHumanoid.rigOf, the string the registry test compares. */
export function rigSha(json: GltfJson): string {
  return createHash('sha256').update(rigOf(json)).digest('hex')
}

/** The commit the producer ran at, or 'uncommitted' outside a checkout. */
export function producedAt(): string {
  try {
    return execFileSync('git', ['rev-parse', '--short', 'HEAD'], { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim()
  } catch {
    return 'uncommitted'
  }
}

/** `/avatar/x.vrm` for a file under public/, else the path as given. */
export function servedPath(file: string): string {
  const rel = path.relative(path.resolve('public'), path.resolve(file))
  return rel.startsWith('..') ? file : `/${rel.split(path.sep).join('/')}`
}

/**
 * Write `export const NAME: Type = {...}` as a generated TypeScript module.
 * JSON is valid TypeScript for an object literal, and a `.gen.ts` under src/
 * is type-checked by the build and importable without resolveJsonModule.
 */
export function writeGenerated(
  file: string,
  opts: { exportName: string; typeName: string; typeFrom: string; producer: string; note: string[] },
  value: unknown,
): void {
  const lines = [
    `// GENERATED by ${opts.producer} — do not edit by hand.`,
    ...opts.note.map((l) => `// ${l}`),
    `import type { ${opts.typeName} } from '${opts.typeFrom}'`,
    '',
    `export const ${opts.exportName}: ${opts.typeName} = ${JSON.stringify(value, null, 2)}`,
    '',
  ]
  mkdirSync(path.dirname(file), { recursive: true })
  writeFileSync(file, lines.join('\n'))
}
