// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/vrm1-twist-sample.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown. Regenerate:
//   npx tsx scripts/measure-motions.ts public/avatar/vrm1-twist-sample.vrm --write src/components/chat/clearance/vrm1-twist-sample.measured.gen.ts --family=vrm1-twist-sample
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vrm1-twist-sample",
  "rigSha": "fd3a65952d9bce0a30feb2a3817b2faedd2168f9145e43f5f48088f218c15e27",
  "measuredOn": "/avatar/vrm1-twist-sample.vrm",
  "producedBy": "571e711",
  "faceBox": {
    "min": [
      -0.1088,
      1.3522,
      -0.0556
    ],
    "max": [
      0.1088,
      1.5855,
      0.0893
    ]
  },
  "handSkinPastTip": 0.0257,
  "restCrownY": 1.6154,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.6531,
        "right": 0.5177
      },
      "skinTop": 1.5101,
      "hipsLow": 0.8505,
      "faceRatio": 1.3704,
      "faceRatioAt": 9.45,
      "endSink": 0.0373,
      "hipsDrift": 0.0147,
      "endWrist": 0.8173
    },
    "modelPose": {
      "reach": {
        "left": 0.3836,
        "right": 0.3483
      },
      "skinTop": 1.3227,
      "hipsLow": 0.8882,
      "faceRatio": 11.644,
      "faceRatioAt": 3.9,
      "endSink": 0.0086,
      "hipsDrift": 0.0269,
      "endWrist": 0.8632
    },
    "spin": {
      "reach": {
        "left": 0.7067,
        "right": 0.5553
      },
      "skinTop": 1.5549,
      "hipsLow": 0.8582,
      "faceRatio": 5.7935,
      "faceRatioAt": 2.45,
      "endSink": 0,
      "hipsDrift": 0.0132,
      "endWrist": 0.8592
    },
    "squat": {
      "reach": {
        "left": 0.6618,
        "right": 0.648
      },
      "skinTop": 1.4317,
      "hipsLow": 0.6825,
      "faceRatio": 1.7035,
      "faceRatioAt": 6.13,
      "endSink": 0,
      "hipsDrift": 0.0106,
      "endWrist": 0.8564
    },
    "akimbo": {
      "reach": {
        "left": 0.3051,
        "right": 0.3326
      },
      "skinTop": 1.0299,
      "hipsLow": 0.9116,
      "faceRatio": 17.0524,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8711
    },
    "playFingers": {
      "reach": {
        "left": 0.2893,
        "right": 0.2908
      },
      "skinTop": 1.0741,
      "hipsLow": 0.9119,
      "faceRatio": 20.0648,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8711
    },
    "scratchHead": {
      "reach": {
        "left": 0.4051,
        "right": 0.5551
      },
      "skinTop": 1.6615,
      "hipsLow": 0.9074,
      "faceRatio": 1.0378,
      "faceRatioAt": 5.37,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8711
    },
    "idleLoop": {
      "reach": {
        "left": 0.4031,
        "right": 0.101
      },
      "skinTop": 0.8606,
      "hipsLow": 0.9058,
      "faceRatio": 31.4717,
      "faceRatioAt": 1.5,
      "endSink": 0.0015,
      "hipsDrift": 0.1573,
      "endWrist": 0.8486
    },
    "stretch": {
      "reach": {
        "left": 0.3573,
        "right": 0.5859
      },
      "skinTop": 1.8758,
      "hipsLow": 0.9124,
      "faceRatio": 2.4876,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8711
    },
    "dance": {
      "reach": {
        "left": 0.7269,
        "right": 0.5392
      },
      "skinTop": 1.5763,
      "hipsLow": 0.7781,
      "faceRatio": 0.2117,
      "faceRatioAt": 8.23,
      "endSink": 0.0487,
      "hipsDrift": 0.1449,
      "endWrist": 1.2358
    }
  }
}
