// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/vrm1-twist-sample.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame. Regenerate:
//   npx tsx scripts/avatar/springsim.ts public/avatar/vrm1-twist-sample.vrm --clearance=src/components/chat/clearance/vrm1-twist-sample.simulated.gen.ts --family=vrm1-twist-sample
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vrm1-twist-sample",
  "rigSha": "fd3a65952d9bce0a30feb2a3817b2faedd2168f9145e43f5f48088f218c15e27",
  "simulatedOn": "/avatar/vrm1-twist-sample.vrm",
  "producedBy": "654ca1f",
  "restCrownY": 1.6154,
  "restCrownScreen": {
    "waistUp": 1.6136,
    "column": 1.6157
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "modelPose": {
        "column": 0.01
      },
      "spin": {
        "column": 0.05
      },
      "squat": {
        "column": 0.03
      },
      "akimbo": {
        "column": 0.03
      },
      "playFingers": {
        "column": 0.03
      },
      "scratchHead": {
        "column": 0.06
      },
      "idleLoop": {
        "column": 0.03
      },
      "stretch": {
        "waistUp": 0.07
      },
      "dance": {
        "column": 0.14
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.6202,
      "crownT": 10.13,
      "crownScreen": {
        "waistUp": 1.6184,
        "column": 1.6208
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 2.8,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.6867,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.719,
        "column": 1.7375
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 35,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.6162,
      "crownT": 5.37,
      "crownScreen": {
        "waistUp": 1.617,
        "column": 1.6225
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 0.7,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.6143,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.6092,
        "column": 1.6086
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 13.7,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.5814,
      "crownT": 0.67,
      "crownScreen": {
        "waistUp": 1.5822,
        "column": 1.5875
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 2.8,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.6228,
      "crownT": 4.57,
      "crownScreen": {
        "waistUp": 1.6226,
        "column": 1.6264
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 2.7,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.6501,
      "crownT": 0.7,
      "crownScreen": {
        "waistUp": 1.6505,
        "column": 1.6535
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 4.9,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.6261,
      "crownT": 6.83,
      "crownScreen": {
        "waistUp": 1.6327,
        "column": 1.6473
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 20.4,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.6268,
      "crownT": 8.17,
      "crownScreen": {
        "waistUp": 1.6208,
        "column": 1.6209
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 11.4,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.8664,
      "crownT": 1.6,
      "crownScreen": {
        "waistUp": 1.8741,
        "column": 1.8896
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 5.2,
      "skirtDepthMm": 0
    }
  }
}
