// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/Victoria_Rubin_webp.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame. Regenerate:
//   npx tsx scripts/avatar/springsim.ts public/avatar/Victoria_Rubin_webp.vrm --clearance=src/components/chat/clearance/vroid-victoria-rubin.simulated.gen.ts --family=vroid-victoria-rubin
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-victoria-rubin",
  "rigSha": "bb4ef1a64fd2c48b7cb9ac3f15e80ce42945ec54d78751bd1d8d9e317afc1b1d",
  "simulatedOn": "/avatar/Victoria_Rubin_webp.vrm",
  "producedBy": "cff0bea",
  "restCrownY": 1.7373,
  "restCrownScreen": {
    "waistUp": 1.7402,
    "column": 1.7457
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "peaceSign": {
        "column": 0.12
      },
      "modelPose": {
        "column": 0.14
      },
      "spin": {
        "column": 0.18
      },
      "squat": {
        "column": 0.15
      },
      "akimbo": {
        "column": 0.15
      },
      "playFingers": {
        "column": 0.16
      },
      "scratchHead": {
        "column": 0.16
      },
      "idleLoop": {
        "column": 0.15
      },
      "stretch": {
        "waistUp": 0.18
      },
      "dance": {
        "column": 0.27
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.7471,
      "crownT": 9.7,
      "crownScreen": {
        "waistUp": 1.7459,
        "column": 1.7478
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 6.9,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.8148,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.864,
        "column": 1.8649
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 43.9,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.7394,
      "crownT": 8.77,
      "crownScreen": {
        "waistUp": 1.7438,
        "column": 1.7469
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 48,
      "jumpDeg": 0.7,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.7362,
      "crownT": 0.53,
      "crownScreen": {
        "waistUp": 1.7367,
        "column": 1.7395
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 12.3,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.7061,
      "crownT": 1.13,
      "crownScreen": {
        "waistUp": 1.7117,
        "column": 1.717
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 6.4,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.7438,
      "crownT": 4.63,
      "crownScreen": {
        "waistUp": 1.7486,
        "column": 1.752
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 1.5,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.7458,
      "crownT": 5.83,
      "crownScreen": {
        "waistUp": 1.7489,
        "column": 1.7517
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 19.2,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.7574,
      "crownT": 2.1,
      "crownScreen": {
        "waistUp": 1.77,
        "column": 1.7762
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 17.8,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.7501,
      "crownT": 8.2,
      "crownScreen": {
        "waistUp": 1.7471,
        "column": 1.7476
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 23.7,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.9714,
      "crownT": 1.67,
      "crownScreen": {
        "waistUp": 1.9798,
        "column": 2.0029
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 24.8,
      "skirtDepthMm": 0
    }
  }
}
