// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/Darkness_Shibu_webp.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown. Regenerate:
//   npx tsx scripts/measure-motions.ts public/avatar/Darkness_Shibu_webp.vrm --write src/components/chat/clearance/vroid-darkness-shibu.measured.gen.ts --family=vroid-darkness-shibu
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-darkness-shibu",
  "rigSha": "a35104318d65138b55226dcb806392a0ee1a16f8e8870736504de8c8fe03ed76",
  "measuredOn": "/avatar/Darkness_Shibu_webp.vrm",
  "producedBy": "8f724ea",
  "faceBox": {
    "min": [
      -0.1066,
      1.3887,
      -0.1067
    ],
    "max": [
      0.1073,
      1.6208,
      0.0401
    ]
  },
  "handSkinPastTip": 0.0208,
  "restCrownY": 1.6501,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.6387,
        "right": 0.5022
      },
      "skinTop": 1.5349,
      "hipsLow": 0.8842,
      "faceRatio": 1.4988,
      "faceRatioAt": 9.45,
      "endSink": 0.0388,
      "hipsDrift": 0.0153,
      "endWrist": 0.8502
    },
    "modelPose": {
      "reach": {
        "left": 0.3699,
        "right": 0.3912
      },
      "skinTop": 1.3702,
      "hipsLow": 0.9234,
      "faceRatio": 9.9984,
      "faceRatioAt": 3.88,
      "endSink": 0.0089,
      "hipsDrift": 0.028,
      "endWrist": 0.896
    },
    "spin": {
      "reach": {
        "left": 0.7077,
        "right": 0.549
      },
      "skinTop": 1.5991,
      "hipsLow": 0.8922,
      "faceRatio": 4.7521,
      "faceRatioAt": 2.43,
      "endSink": 0,
      "hipsDrift": 0.0137,
      "endWrist": 0.8956
    },
    "squat": {
      "reach": {
        "left": 0.6565,
        "right": 0.643
      },
      "skinTop": 1.4483,
      "hipsLow": 0.7095,
      "faceRatio": 1.6795,
      "faceRatioAt": 6.12,
      "endSink": 0,
      "hipsDrift": 0.011,
      "endWrist": 0.892
    },
    "akimbo": {
      "reach": {
        "left": 0.2894,
        "right": 0.3627
      },
      "skinTop": 1.0743,
      "hipsLow": 0.9477,
      "faceRatio": 16.1286,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8993
    },
    "playFingers": {
      "reach": {
        "left": 0.3077,
        "right": 0.3077
      },
      "skinTop": 1.1209,
      "hipsLow": 0.948,
      "faceRatio": 19.4956,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8993
    },
    "scratchHead": {
      "reach": {
        "left": 0.453,
        "right": 0.5434
      },
      "skinTop": 1.6797,
      "hipsLow": 0.9433,
      "faceRatio": 0.7622,
      "faceRatioAt": 4.3,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8993
    },
    "idleLoop": {
      "reach": {
        "left": 0.4042,
        "right": 0.0949
      },
      "skinTop": 0.8981,
      "hipsLow": 0.9417,
      "faceRatio": 31.6481,
      "faceRatioAt": 1.54,
      "endSink": 0.0016,
      "hipsDrift": 0.1635,
      "endWrist": 0.8845
    },
    "stretch": {
      "reach": {
        "left": 0.3827,
        "right": 0.5721
      },
      "skinTop": 1.9088,
      "hipsLow": 0.9485,
      "faceRatio": 2.4637,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8993
    },
    "dance": {
      "reach": {
        "left": 0.746,
        "right": 0.534
      },
      "skinTop": 1.5935,
      "hipsLow": 0.8089,
      "faceRatio": 0.1897,
      "faceRatioAt": 8.23,
      "endSink": 0.0506,
      "hipsDrift": 0.1507,
      "endWrist": 1.2716
    }
  }
}
