// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/mika-glasses_webp-2.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/avatar/springsim.ts public/avatar/mika-glasses_webp-2.vrm --clearance=src/components/chat/clearance/vroid-mika-glasses.simulated.gen.ts --family=vroid-mika-glasses
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-mika-glasses",
  "rigSha": "d226731cb2298d6fc18d4cc7d4f6840b48131ccbc4da2b95fed7096e895853b5",
  "simulatedOn": "/avatar/mika-glasses_webp-2.vrm",
  "producedBy": "d0e9d1b",
  "restCrownY": 1.582,
  "restCrownScreen": {
    "waistUp": 1.5822,
    "column": 1.5847
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "spin": {
        "column": 0.03
      },
      "scratchHead": {
        "column": 0.03
      },
      "dance": {
        "column": 0.12
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.587,
      "crownT": 10.07,
      "crownScreen": {
        "waistUp": 1.5869,
        "column": 1.5902
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.6,
      "jumpDeg": 2.7,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.6605,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.695,
        "column": 1.719
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.8,
      "jumpDeg": 26.9,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.583,
      "crownT": 5.37,
      "crownScreen": {
        "waistUp": 1.5856,
        "column": 1.5924
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.8,
      "jumpDeg": 6.4,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.5789,
      "crownT": 0.53,
      "crownScreen": {
        "waistUp": 1.576,
        "column": 1.5775
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.7,
      "jumpDeg": 4.5,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.5478,
      "crownT": 0.1,
      "crownScreen": {
        "waistUp": 1.5498,
        "column": 1.5564
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.7,
      "jumpDeg": 8.2,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.5886,
      "crownT": 3.73,
      "crownScreen": {
        "waistUp": 1.5882,
        "column": 1.5938
      },
      "coatDepthMm": 0,
      "bodyDepthMm": -50,
      "jumpDeg": 0.4,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.6223,
      "crownT": 0.7,
      "crownScreen": {
        "waistUp": 1.6225,
        "column": 1.6258
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 2.9,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.5949,
      "crownT": 6.83,
      "crownScreen": {
        "waistUp": 1.5974,
        "column": 1.6188
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 47.5,
      "jumpDeg": 19.9,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.5963,
      "crownT": 8.17,
      "crownScreen": {
        "waistUp": 1.5912,
        "column": 1.5904
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 6.4,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.8341,
      "crownT": 1.6,
      "crownScreen": {
        "waistUp": 1.843,
        "column": 1.8551
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 2.2,
      "skirtDepthMm": 0
    }
  }
}
