// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/Victoria_Rubin_webp.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/measure-motions.ts public/avatar/Victoria_Rubin_webp.vrm --write src/components/chat/clearance/vroid-victoria-rubin.measured.gen.ts --family=vroid-victoria-rubin
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-victoria-rubin",
  "rigSha": "bb4ef1a64fd2c48b7cb9ac3f15e80ce42945ec54d78751bd1d8d9e317afc1b1d",
  "measuredOn": "/avatar/Victoria_Rubin_webp.vrm",
  "producedBy": "d89982b",
  "faceBox": {
    "min": [
      -0.1077,
      1.4655,
      -0.1108
    ],
    "max": [
      0.1087,
      1.7032,
      0.0384
    ]
  },
  "handSkinPastTip": 0.0208,
  "restCrownY": 1.7373,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.6411,
        "right": 0.4986
      },
      "skinTop": 1.6031,
      "hipsLow": 0.9457,
      "faceRatio": 1.4621,
      "faceRatioAt": 9.45,
      "endSink": 0.0415,
      "hipsDrift": 0.0164,
      "endWrist": 0.9185
    },
    "modelPose": {
      "reach": {
        "left": 0.4106,
        "right": 0.3941
      },
      "skinTop": 1.4398,
      "hipsLow": 0.9877,
      "faceRatio": 9.841,
      "faceRatioAt": 3.88,
      "endSink": 0.0095,
      "hipsDrift": 0.0299,
      "endWrist": 0.9664
    },
    "spin": {
      "reach": {
        "left": 0.7126,
        "right": 0.5451
      },
      "skinTop": 1.6699,
      "hipsLow": 0.9543,
      "faceRatio": 4.8057,
      "faceRatioAt": 2.43,
      "endSink": 0,
      "hipsDrift": 0.0147,
      "endWrist": 0.9669
    },
    "squat": {
      "reach": {
        "left": 0.657,
        "right": 0.6434
      },
      "skinTop": 1.5199,
      "hipsLow": 0.7589,
      "faceRatio": 1.7375,
      "faceRatioAt": 6.12,
      "endSink": 0,
      "hipsDrift": 0.0117,
      "endWrist": 0.9634
    },
    "akimbo": {
      "reach": {
        "left": 0.2888,
        "right": 0.3661
      },
      "skinTop": 1.1456,
      "hipsLow": 1.0137,
      "faceRatio": 15.9765,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.9706
    },
    "playFingers": {
      "reach": {
        "left": 0.3076,
        "right": 0.3078
      },
      "skinTop": 1.1922,
      "hipsLow": 1.014,
      "faceRatio": 19.1591,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.9706
    },
    "scratchHead": {
      "reach": {
        "left": 0.4562,
        "right": 0.5417
      },
      "skinTop": 1.7506,
      "hipsLow": 1.0089,
      "faceRatio": 0.6169,
      "faceRatioAt": 4.3,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.9706
    },
    "idleLoop": {
      "reach": {
        "left": 0.4512,
        "right": 0.1197
      },
      "skinTop": 0.9691,
      "hipsLow": 1.0073,
      "faceRatio": 30.9828,
      "faceRatioAt": 1.54,
      "endSink": 0.0017,
      "hipsDrift": 0.1749,
      "endWrist": 0.9554
    },
    "stretch": {
      "reach": {
        "left": 0.3836,
        "right": 0.5713
      },
      "skinTop": 1.981,
      "hipsLow": 1.0145,
      "faceRatio": 2.3987,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.9706
    },
    "dance": {
      "reach": {
        "left": 0.76,
        "right": 0.56
      },
      "skinTop": 1.6668,
      "hipsLow": 0.8652,
      "faceRatio": 0.2239,
      "faceRatioAt": 8.23,
      "endSink": 0.0541,
      "hipsDrift": 0.1612,
      "endWrist": 1.3392
    },
    "groove": {
      "reach": {
        "left": 0.4485,
        "right": 0.6086
      },
      "skinTop": 1.2119,
      "hipsLow": 0.8042,
      "faceRatio": 3.6469,
      "faceRatioAt": 1.53,
      "endSink": 0.0113,
      "hipsDrift": 0.0002,
      "endWrist": 0.9418
    },
    "macarena": {
      "reach": {
        "left": 0.4716,
        "right": 0.4247
      },
      "skinTop": 1.629,
      "hipsLow": 0.6621,
      "faceRatio": 0.1595,
      "faceRatioAt": 4.13,
      "endSink": 0.0793,
      "hipsDrift": 0.0022,
      "endWrist": 1.1352
    },
    "catwalk": {
      "reach": {
        "left": 0.554,
        "right": 0.4892
      },
      "skinTop": 1.2734,
      "hipsLow": 0.9396,
      "faceRatio": 13.5198,
      "faceRatioAt": 6.53,
      "endSink": 0.0404,
      "hipsDrift": 0.0043,
      "endWrist": 1.0057
    },
    "jumpAround": {
      "reach": {
        "left": 0.5542,
        "right": 0.3473
      },
      "skinTop": 1.6948,
      "hipsLow": 0.9157,
      "faceRatio": 14.2981,
      "faceRatioAt": 4.27,
      "endSink": 0.0113,
      "hipsDrift": 0.0002,
      "endWrist": 0.9418
    },
    "cheer": {
      "reach": {
        "left": 0.4156,
        "right": 0.5861
      },
      "skinTop": 1.9183,
      "hipsLow": 0.7782,
      "faceRatio": 2.2906,
      "faceRatioAt": 3.87,
      "endSink": 0.0113,
      "hipsDrift": 0.0002,
      "endWrist": 0.9418
    },
    "shyPose": {
      "reach": {
        "left": 0.442,
        "right": 0.2914
      },
      "skinTop": 1.3967,
      "hipsLow": 0.9385,
      "faceRatio": 1.8079,
      "faceRatioAt": 2.43,
      "endSink": 0.0113,
      "hipsDrift": 0.0002,
      "endWrist": 0.9418
    }
  }
}
