// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/vroid-studio-dressup.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/measure-motions.ts public/avatar/vroid-studio-dressup.vrm --write src/components/chat/clearance/vroid-studio-dressup.measured.gen.ts --family=vroid-studio-dressup
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-studio-dressup",
  "rigSha": "ec3b9ab3648bcaea26792c0324d32f7fabda1245a58813a0139af5c00032491e",
  "measuredOn": "/avatar/vroid-studio-dressup.vrm",
  "producedBy": "d89982b",
  "faceBox": {
    "min": [
      -0.1088,
      1.3522,
      -0.0556
    ],
    "max": [
      0.1088,
      1.5855,
      0.0893
    ]
  },
  "handSkinPastTip": 0.0197,
  "restCrownY": 1.5982,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.652,
        "right": 0.5081
      },
      "skinTop": 1.4912,
      "hipsLow": 0.8505,
      "faceRatio": 1.4982,
      "faceRatioAt": 9.45,
      "endSink": 0.0373,
      "hipsDrift": 0.0147,
      "endWrist": 0.8173
    },
    "modelPose": {
      "reach": {
        "left": 0.3855,
        "right": 0.3849
      },
      "skinTop": 1.3111,
      "hipsLow": 0.8882,
      "faceRatio": 12.6717,
      "faceRatioAt": 3.95,
      "endSink": 0.0086,
      "hipsDrift": 0.0269,
      "endWrist": 0.865
    },
    "spin": {
      "reach": {
        "left": 0.7025,
        "right": 0.5572
      },
      "skinTop": 1.5211,
      "hipsLow": 0.8582,
      "faceRatio": 6.3797,
      "faceRatioAt": 2.45,
      "endSink": 0,
      "hipsDrift": 0.0132,
      "endWrist": 0.8587
    },
    "squat": {
      "reach": {
        "left": 0.6659,
        "right": 0.6619
      },
      "skinTop": 1.4318,
      "hipsLow": 0.6825,
      "faceRatio": 1.6796,
      "faceRatioAt": 6.07,
      "endSink": 0,
      "hipsDrift": 0.0106,
      "endWrist": 0.8567
    },
    "akimbo": {
      "reach": {
        "left": 0.3119,
        "right": 0.3637
      },
      "skinTop": 1.0309,
      "hipsLow": 0.9116,
      "faceRatio": 16.9574,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.871
    },
    "playFingers": {
      "reach": {
        "left": 0.3089,
        "right": 0.3088
      },
      "skinTop": 1.0742,
      "hipsLow": 0.9119,
      "faceRatio": 20.1034,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.871
    },
    "scratchHead": {
      "reach": {
        "left": 0.453,
        "right": 0.5507
      },
      "skinTop": 1.6388,
      "hipsLow": 0.9074,
      "faceRatio": 1.2478,
      "faceRatioAt": 4.32,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.871
    },
    "idleLoop": {
      "reach": {
        "left": 0.4129,
        "right": 0.0944
      },
      "skinTop": 0.8607,
      "hipsLow": 0.9058,
      "faceRatio": 31.4641,
      "faceRatioAt": 1.5,
      "endSink": 0.0015,
      "hipsDrift": 0.1573,
      "endWrist": 0.8487
    },
    "stretch": {
      "reach": {
        "left": 0.3812,
        "right": 0.6004
      },
      "skinTop": 1.8631,
      "hipsLow": 0.9124,
      "faceRatio": 2.6615,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.871
    },
    "dance": {
      "reach": {
        "left": 0.722,
        "right": 0.552
      },
      "skinTop": 1.5537,
      "hipsLow": 0.7781,
      "faceRatio": 0.4058,
      "faceRatioAt": 8.23,
      "endSink": 0.0487,
      "hipsDrift": 0.1449,
      "endWrist": 1.2358
    },
    "groove": {
      "reach": {
        "left": 0.4526,
        "right": 0.5923
      },
      "skinTop": 1.1148,
      "hipsLow": 0.7232,
      "faceRatio": 4.5254,
      "faceRatioAt": 1.53,
      "endSink": 0.0102,
      "hipsDrift": 0.0002,
      "endWrist": 0.8399
    },
    "macarena": {
      "reach": {
        "left": 0.4855,
        "right": 0.4204
      },
      "skinTop": 1.5572,
      "hipsLow": 0.5954,
      "faceRatio": 0.5524,
      "faceRatioAt": 4.3,
      "endSink": 0.0713,
      "hipsDrift": 0.002,
      "endWrist": 1.0223
    },
    "catwalk": {
      "reach": {
        "left": 0.5486,
        "right": 0.5179
      },
      "skinTop": 1.166,
      "hipsLow": 0.845,
      "faceRatio": 15.7331,
      "faceRatioAt": 6.57,
      "endSink": 0.0364,
      "hipsDrift": 0.0039,
      "endWrist": 0.8844
    },
    "jumpAround": {
      "reach": {
        "left": 0.5638,
        "right": 0.3756
      },
      "skinTop": 1.5565,
      "hipsLow": 0.8235,
      "faceRatio": 15.2432,
      "faceRatioAt": 3.3,
      "endSink": 0.0102,
      "hipsDrift": 0.0002,
      "endWrist": 0.8399
    },
    "cheer": {
      "reach": {
        "left": 0.4222,
        "right": 0.5777
      },
      "skinTop": 1.7952,
      "hipsLow": 0.6999,
      "faceRatio": 3.7746,
      "faceRatioAt": 3.87,
      "endSink": 0.0102,
      "hipsDrift": 0.0002,
      "endWrist": 0.8399
    },
    "shyPose": {
      "reach": {
        "left": 0.4391,
        "right": 0.3097
      },
      "skinTop": 1.2702,
      "hipsLow": 0.844,
      "faceRatio": 3.2767,
      "faceRatioAt": 2.47,
      "endSink": 0.0102,
      "hipsDrift": 0.0002,
      "endWrist": 0.8399
    }
  }
}
