// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/gishin-2.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/measure-motions.ts public/avatar/gishin-2.vrm --write src/components/chat/clearance/vroid-gishin.measured.gen.ts --family=vroid-gishin
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-gishin",
  "rigSha": "df0054aa866f68a8b95510bad358a5d43bced092ee396e35415068614d29b1ba",
  "measuredOn": "/avatar/gishin-2.vrm",
  "producedBy": "afc79f2",
  "faceBox": {
    "min": [
      -0.1029,
      1.3314,
      -0.0869
    ],
    "max": [
      0.1035,
      1.5528,
      0.0541
    ]
  },
  "handSkinPastTip": 0.0193,
  "restCrownY": 1.582,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.6371,
        "right": 0.4957
      },
      "skinTop": 1.4646,
      "hipsLow": 0.8384,
      "faceRatio": 1.5659,
      "faceRatioAt": 9.45,
      "endSink": 0.0368,
      "hipsDrift": 0.0145,
      "endWrist": 0.8062
    },
    "modelPose": {
      "reach": {
        "left": 0.3759,
        "right": 0.3402
      },
      "skinTop": 1.2854,
      "hipsLow": 0.8756,
      "faceRatio": 13.098,
      "faceRatioAt": 3.93,
      "endSink": 0.0084,
      "hipsDrift": 0.0265,
      "endWrist": 0.8513
    },
    "spin": {
      "reach": {
        "left": 0.6878,
        "right": 0.5413
      },
      "skinTop": 1.5081,
      "hipsLow": 0.846,
      "faceRatio": 6.62,
      "faceRatioAt": 2.45,
      "endSink": 0,
      "hipsDrift": 0.013,
      "endWrist": 0.8476
    },
    "squat": {
      "reach": {
        "left": 0.6509,
        "right": 0.6462
      },
      "skinTop": 1.4062,
      "hipsLow": 0.6727,
      "faceRatio": 1.752,
      "faceRatioAt": 6.13,
      "endSink": 0,
      "hipsDrift": 0.0104,
      "endWrist": 0.8448
    },
    "akimbo": {
      "reach": {
        "left": 0.3045,
        "right": 0.3289
      },
      "skinTop": 1.0154,
      "hipsLow": 0.8987,
      "faceRatio": 17.8824,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.859
    },
    "playFingers": {
      "reach": {
        "left": 0.2904,
        "right": 0.2917
      },
      "skinTop": 1.0577,
      "hipsLow": 0.8989,
      "faceRatio": 20.7496,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.859
    },
    "scratchHead": {
      "reach": {
        "left": 0.4017,
        "right": 0.5377
      },
      "skinTop": 1.609,
      "hipsLow": 0.8945,
      "faceRatio": 1.3341,
      "faceRatioAt": 4.3,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.859
    },
    "idleLoop": {
      "reach": {
        "left": 0.4047,
        "right": 0.0942
      },
      "skinTop": 0.849,
      "hipsLow": 0.893,
      "faceRatio": 33.2717,
      "faceRatioAt": 1.5,
      "endSink": 0.0015,
      "hipsDrift": 0.1551,
      "endWrist": 0.837
    },
    "stretch": {
      "reach": {
        "left": 0.3559,
        "right": 0.5863
      },
      "skinTop": 1.8282,
      "hipsLow": 0.8994,
      "faceRatio": 2.681,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.859
    },
    "dance": {
      "reach": {
        "left": 0.707,
        "right": 0.5293
      },
      "skinTop": 1.5262,
      "hipsLow": 0.767,
      "faceRatio": 0.4252,
      "faceRatioAt": 8.23,
      "endSink": 0.048,
      "hipsDrift": 0.1429,
      "endWrist": 1.2147
    },
    "waveWink": {
      "reach": {
        "left": 0.3659,
        "right": 0.2819
      },
      "skinTop": 1.4181,
      "hipsLow": 0.8952,
      "faceRatio": 3.2636,
      "faceRatioAt": 1.6,
      "endSink": 0,
      "hipsDrift": 0,
      "endWrist": 0.8502
    }
  }
}
