// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/Darkness_Shibu_webp.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame. Regenerate:
//   npx tsx scripts/avatar/springsim.ts public/avatar/Darkness_Shibu_webp.vrm --clearance=src/components/chat/clearance/vroid-darkness-shibu.simulated.gen.ts --family=vroid-darkness-shibu
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-darkness-shibu",
  "rigSha": "a35104318d65138b55226dcb806392a0ee1a16f8e8870736504de8c8fe03ed76",
  "simulatedOn": "/avatar/Darkness_Shibu_webp.vrm",
  "producedBy": "e0e541d",
  "restCrownY": 1.6501,
  "restCrownScreen": {
    "waistUp": 1.651,
    "column": 1.6576
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "peaceSign": {
        "column": 0.03
      },
      "modelPose": {
        "column": 0.05
      },
      "spin": {
        "column": 0.1
      },
      "squat": {
        "column": 0.07
      },
      "akimbo": {
        "column": 0.07
      },
      "playFingers": {
        "column": 0.07
      },
      "scratchHead": {
        "column": 0.08
      },
      "idleLoop": {
        "column": 0.07
      },
      "stretch": {
        "waistUp": 0.11
      },
      "dance": {
        "column": 0.18
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.6552,
      "crownT": 10.1,
      "crownScreen": {
        "waistUp": 1.6559,
        "column": 1.6609
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 3.3,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.7285,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.7643,
        "column": 1.7772
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 35.5,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.6506,
      "crownT": 5.37,
      "crownScreen": {
        "waistUp": 1.655,
        "column": 1.6623
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 17.7,
      "jumpDeg": 0.6,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.6488,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.6445,
        "column": 1.6483
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 3.8,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.6144,
      "crownT": 0.67,
      "crownScreen": {
        "waistUp": 1.6173,
        "column": 1.6254
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 2,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.6575,
      "crownT": 4.53,
      "crownScreen": {
        "waistUp": 1.6592,
        "column": 1.6641
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 19,
      "jumpDeg": 1.6,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.668,
      "crownT": 0.67,
      "crownScreen": {
        "waistUp": 1.6718,
        "column": 1.6768
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 3.3,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.6607,
      "crownT": 6.83,
      "crownScreen": {
        "waistUp": 1.6711,
        "column": 1.6903
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 17.5,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.6636,
      "crownT": 8.2,
      "crownScreen": {
        "waistUp": 1.6592,
        "column": 1.6616
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 8.8,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.8993,
      "crownT": 1.67,
      "crownScreen": {
        "waistUp": 1.9074,
        "column": 1.9261
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.2,
      "jumpDeg": 4,
      "skirtDepthMm": 0
    }
  }
}
