// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/Sendagaya_Shino_webp.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame. Regenerate:
//   npx tsx scripts/avatar/springsim.ts public/avatar/Sendagaya_Shino_webp.vrm --clearance=src/components/chat/clearance/vroid-sendagaya-shino.simulated.gen.ts --family=vroid-sendagaya-shino
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-sendagaya-shino",
  "rigSha": "ba2bf7326d1807b0d352a4b81a68f2024ca94c449224448bdb94c48d97912965",
  "simulatedOn": "/avatar/Sendagaya_Shino_webp.vrm",
  "producedBy": "1602992",
  "restCrownY": 1.6451,
  "restCrownScreen": {
    "waistUp": 1.646,
    "column": 1.6498
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "peaceSign": {
        "column": 0.02
      },
      "modelPose": {
        "column": 0.05
      },
      "spin": {
        "column": 0.09
      },
      "squat": {
        "column": 0.06
      },
      "akimbo": {
        "column": 0.06
      },
      "playFingers": {
        "column": 0.06
      },
      "scratchHead": {
        "column": 0.07
      },
      "idleLoop": {
        "column": 0.06
      },
      "stretch": {
        "waistUp": 0.1
      },
      "dance": {
        "column": 0.18
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.6503,
      "crownT": 0.2,
      "crownScreen": {
        "waistUp": 1.6507,
        "column": 1.6539
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 6.4,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.7196,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.7567,
        "column": 1.7696
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 48.9,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.6458,
      "crownT": 5.37,
      "crownScreen": {
        "waistUp": 1.6497,
        "column": 1.6552
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 47,
      "jumpDeg": 0.9,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.642,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.6395,
        "column": 1.643
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.8,
      "jumpDeg": 10.3,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.609,
      "crownT": 0.7,
      "crownScreen": {
        "waistUp": 1.6127,
        "column": 1.6204
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 8.4,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.651,
      "crownT": 4.67,
      "crownScreen": {
        "waistUp": 1.6539,
        "column": 1.6595
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 3.4,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.6611,
      "crownT": 0.67,
      "crownScreen": {
        "waistUp": 1.6647,
        "column": 1.6699
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 8.6,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.6526,
      "crownT": 6.83,
      "crownScreen": {
        "waistUp": 1.665,
        "column": 1.684
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 17.5,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.6582,
      "crownT": 8.17,
      "crownScreen": {
        "waistUp": 1.6526,
        "column": 1.6532
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 21.6,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.8921,
      "crownT": 1.67,
      "crownScreen": {
        "waistUp": 1.9003,
        "column": 1.9182
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.7,
      "jumpDeg": 9.7,
      "skirtDepthMm": 0
    }
  }
}
