// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/Vivi_webp.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame. Regenerate:
//   npx tsx scripts/avatar/springsim.ts public/avatar/Vivi_webp.vrm --clearance=src/components/chat/clearance/vroid-vivi.simulated.gen.ts --family=vroid-vivi
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-vivi",
  "rigSha": "4e782ba7af36e3e8059ce4b3fecd6ac2d4fc1ba782846fd104fb8e9a3f9e9daa",
  "simulatedOn": "/avatar/Vivi_webp.vrm",
  "producedBy": "cff0bea",
  "restCrownY": 1.4122,
  "restCrownScreen": {
    "waistUp": 1.4119,
    "column": 1.4222
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "peaceSign": {
        "waistUp": -0.26
      },
      "modelPose": {
        "waistUp": -0.23
      },
      "spin": {
        "waistUp": -0.24
      },
      "dance": {
        "waistUp": -0.23
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.4168,
      "crownT": 10.13,
      "crownScreen": {
        "waistUp": 1.4168,
        "column": 1.4265
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 48.9,
      "jumpDeg": 2.4,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.4814,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.5044,
        "column": 1.5088
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 36.6,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.4136,
      "crownT": 6.23,
      "crownScreen": {
        "waistUp": 1.4133,
        "column": 1.4267
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.5,
      "jumpDeg": 0.4,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.4054,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.4087,
        "column": 1.4104
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 2.6,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.3805,
      "crownT": 0.73,
      "crownScreen": {
        "waistUp": 1.3913,
        "column": 1.3928
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.8,
      "jumpDeg": 4,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.4162,
      "crownT": 0.03,
      "crownScreen": {
        "waistUp": 1.416,
        "column": 1.4268
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 2.8,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.4165,
      "crownT": 0.03,
      "crownScreen": {
        "waistUp": 1.4163,
        "column": 1.4272
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.7,
      "jumpDeg": 27.7,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.4166,
      "crownT": 1.97,
      "crownScreen": {
        "waistUp": 1.4301,
        "column": 1.4333
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 21.1,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.4321,
      "crownT": 8.27,
      "crownScreen": {
        "waistUp": 1.4321,
        "column": 1.4331
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 7.2,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.5924,
      "crownT": 1.7,
      "crownScreen": {
        "waistUp": 1.5942,
        "column": 1.6018
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.8,
      "jumpDeg": 6.4,
      "skirtDepthMm": 0
    }
  }
}
