// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/AvatarSample_C_webp.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame. Regenerate:
//   npx tsx scripts/avatar/springsim.ts public/avatar/AvatarSample_C_webp.vrm --clearance=src/components/chat/clearance/vroid-sample-c.simulated.gen.ts --family=vroid-sample-c
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-sample-c",
  "rigSha": "6c651594cc59fb032affe7ea165d0562115632aa863b3ea12069cb713e2bc961",
  "simulatedOn": "/avatar/AvatarSample_C_webp.vrm",
  "producedBy": "cff0bea",
  "restCrownY": 1.7561,
  "restCrownScreen": {
    "waistUp": 1.7633,
    "column": 1.7763
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "peaceSign": {
        "column": 0.14
      },
      "modelPose": {
        "column": 0.16
      },
      "spin": {
        "column": 0.27
      },
      "squat": {
        "column": 0.18
      },
      "akimbo": {
        "column": 0.18
      },
      "playFingers": {
        "column": 0.18
      },
      "scratchHead": {
        "column": 0.27
      },
      "idleLoop": {
        "column": 0.18
      },
      "stretch": {
        "waistUp": 0.24
      },
      "dance": {
        "waistUp": 0.06,
        "column": 0.3
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.7616,
      "crownT": 10.17,
      "crownScreen": {
        "waistUp": 1.7685,
        "column": 1.7727
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 48.9,
      "jumpDeg": 2.8,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.845,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.8861,
        "column": 1.8908
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 19.1,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.7553,
      "crownT": 5.37,
      "crownScreen": {
        "waistUp": 1.7669,
        "column": 1.7723
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 25.6,
      "jumpDeg": 0.4,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.7505,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.7496,
        "column": 1.7539
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.3,
      "jumpDeg": 1.8,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.7166,
      "crownT": 0.63,
      "crownScreen": {
        "waistUp": 1.7253,
        "column": 1.7386
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 2.3,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.7628,
      "crownT": 4.57,
      "crownScreen": {
        "waistUp": 1.7692,
        "column": 1.7732
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 26.1,
      "jumpDeg": 1.2,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.8464,
      "crownT": 0.67,
      "crownScreen": {
        "waistUp": 1.8615,
        "column": 1.8618
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 48.9,
      "jumpDeg": 2.3,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.7637,
      "crownT": 6.83,
      "crownScreen": {
        "waistUp": 1.857,
        "column": 1.8594
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 14.6,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.7695,
      "crownT": 8.2,
      "crownScreen": {
        "waistUp": 1.7686,
        "column": 1.7717
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.1,
      "jumpDeg": 6.7,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 2.0856,
      "crownT": 1.7,
      "crownScreen": {
        "waistUp": 2.0987,
        "column": 2.1314
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.3,
      "jumpDeg": 3.2,
      "skirtDepthMm": 0
    }
  }
}
