// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/gishin_webp.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/avatar/springsim.ts public/avatar/gishin_webp.vrm --clearance=src/components/chat/clearance/vroid-gishin.simulated.gen.ts --family=vroid-gishin
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-gishin",
  "rigSha": "0b931951c9cf18b3269c72941cb1f557edef03f782027b3a691b83dbd52fbecf",
  "simulatedOn": "/avatar/gishin_webp.vrm",
  "producedBy": "048ea32",
  "restCrownY": 1.582,
  "restCrownScreen": {
    "waistUp": 1.5814,
    "column": 1.5859
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "spin": {
        "column": 0.03
      },
      "scratchHead": {
        "column": 0.03
      },
      "dance": {
        "waistUp": -0.08,
        "column": 0.12
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.5869,
      "crownT": 10.1,
      "crownScreen": {
        "waistUp": 1.5861,
        "column": 1.5914
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 46.7,
      "jumpDeg": 2.8,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.6569,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.6932,
        "column": 1.7032
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 22.1,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.5827,
      "crownT": 5.37,
      "crownScreen": {
        "waistUp": 1.5847,
        "column": 1.5933
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 40.7,
      "jumpDeg": 0.4,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.5809,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.5766,
        "column": 1.5765
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 2.3,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.5486,
      "crownT": 0.67,
      "crownScreen": {
        "waistUp": 1.5492,
        "column": 1.5564
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49,
      "jumpDeg": 2.1,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.5895,
      "crownT": 0.37,
      "crownScreen": {
        "waistUp": 1.5889,
        "column": 1.5931
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 19.5,
      "jumpDeg": 1.8,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.6194,
      "crownT": 0.7,
      "crownScreen": {
        "waistUp": 1.6196,
        "column": 1.6229
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.2,
      "jumpDeg": 3.1,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.5929,
      "crownT": 6.83,
      "crownScreen": {
        "waistUp": 1.5982,
        "column": 1.6151
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 15.3,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.5955,
      "crownT": 8.2,
      "crownScreen": {
        "waistUp": 1.5921,
        "column": 1.5924
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 4.5,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.8309,
      "crownT": 1.6,
      "crownScreen": {
        "waistUp": 1.8396,
        "column": 1.8517
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 45.9,
      "jumpDeg": 4.6,
      "skirtDepthMm": 0
    }
  }
}
