// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/mika-milfy-12.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame. Regenerate:
//   npx tsx scripts/avatar/springsim.ts public/avatar/mika-milfy-12.vrm --clearance=src/components/chat/clearance/vroid-sample-b.simulated.gen.ts
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-sample-b",
  "rigSha": "e2aad79ec6667a5529934359339a6a08a29f73fe8a51f5cc6d4d702e137c1b45",
  "simulatedOn": "/avatar/mika-milfy-12.vrm",
  "producedBy": "a9628b9",
  "restCrownY": 1.5757,
  "restCrownScreen": {
    "waistUp": 1.5786,
    "column": 1.5881
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "dance": {
        "waistUp": -0.08,
        "column": 0.13
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.5833,
      "crownT": 0.5,
      "crownScreen": {
        "waistUp": 1.5837,
        "column": 1.593
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 39.5,
      "jumpDeg": 2.5,
      "skirtDepthMm": -19
    },
    "dance": {
      "crownY": 1.6647,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.7013,
        "column": 1.7099
      },
      "coatDepthMm": 37.5,
      "bodyDepthMm": 50,
      "jumpDeg": 21.7,
      "skirtDepthMm": 18.3
    },
    "idleLoop": {
      "crownY": 1.5774,
      "crownT": 1.2,
      "crownScreen": {
        "waistUp": 1.582,
        "column": 1.5965
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 4.8,
      "jumpDeg": 0.3,
      "skirtDepthMm": -18.8
    },
    "modelPose": {
      "crownY": 1.5754,
      "crownT": 0.5,
      "crownScreen": {
        "waistUp": 1.5728,
        "column": 1.577
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 15.9,
      "jumpDeg": 5,
      "skirtDepthMm": -19
    },
    "peaceSign": {
      "crownY": 1.5463,
      "crownT": 0.77,
      "crownScreen": {
        "waistUp": 1.5476,
        "column": 1.5578
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 4.5,
      "skirtDepthMm": -19
    },
    "playFingers": {
      "crownY": 1.5822,
      "crownT": 4.6,
      "crownScreen": {
        "waistUp": 1.5835,
        "column": 1.5936
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 4.8,
      "jumpDeg": 1.9,
      "skirtDepthMm": -19.2
    },
    "scratchHead": {
      "crownY": 1.583,
      "crownT": 5.83,
      "crownScreen": {
        "waistUp": 1.5835,
        "column": 1.5933
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 3.5,
      "skirtDepthMm": -19.2
    },
    "spin": {
      "crownY": 1.5886,
      "crownT": 6.83,
      "crownScreen": {
        "waistUp": 1.5958,
        "column": 1.6107
      },
      "coatDepthMm": 41.8,
      "bodyDepthMm": 4.8,
      "jumpDeg": 12.4,
      "skirtDepthMm": -19
    },
    "squat": {
      "crownY": 1.5928,
      "crownT": 8.2,
      "crownScreen": {
        "waistUp": 1.5918,
        "column": 1.5944
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 4.8,
      "jumpDeg": 12.7,
      "skirtDepthMm": -19
    },
    "stretch": {
      "crownY": 1.7992,
      "crownT": 1.8,
      "crownScreen": {
        "waistUp": 1.8081,
        "column": 1.8213
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 4.8,
      "jumpDeg": 3.5,
      "skirtDepthMm": -19.1
    }
  }
}
