// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/Vita_webp.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/avatar/springsim.ts public/avatar/Vita_webp.vrm --clearance=src/components/chat/clearance/vroid-vita.simulated.gen.ts --family=vroid-vita
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-vita",
  "rigSha": "7d04404f31887fd4d4f64032179ec1bbc3a99f11294bbc2635096714fb913702",
  "simulatedOn": "/avatar/Vita_webp.vrm",
  "producedBy": "d89982b",
  "restCrownY": 1.713,
  "restCrownScreen": {
    "waistUp": 1.7179,
    "column": 1.7262
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "peaceSign": {
        "column": 0.1
      },
      "modelPose": {
        "column": 0.12
      },
      "spin": {
        "column": 0.15
      },
      "squat": {
        "column": 0.13
      },
      "akimbo": {
        "column": 0.13
      },
      "playFingers": {
        "column": 0.13
      },
      "scratchHead": {
        "column": 0.13
      },
      "idleLoop": {
        "column": 0.13
      },
      "stretch": {
        "waistUp": 0.15
      },
      "dance": {
        "waistUp": 0.04,
        "column": 0.28
      },
      "groove": {
        "column": 0.18
      },
      "macarena": {
        "waistUp": -0.11,
        "column": 0.16
      },
      "catwalk": {
        "column": 0.14
      },
      "jumpAround": {
        "waistUp": 0.23,
        "column": 0.49
      },
      "cheer": {
        "waistUp": 0.09,
        "column": 0.34
      },
      "shyPose": {
        "column": 0.13
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.7216,
      "crownT": 0.67,
      "crownScreen": {
        "waistUp": 1.7232,
        "column": 1.7272
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 3.7,
      "skirtDepthMm": 0
    },
    "catwalk": {
      "crownY": 1.7111,
      "crownT": 11.53,
      "crownScreen": {
        "waistUp": 1.7169,
        "column": 1.7312
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 24.8,
      "skirtDepthMm": 0
    },
    "cheer": {
      "crownY": 1.8785,
      "crownT": 1.97,
      "crownScreen": {
        "waistUp": 1.9244,
        "column": 1.93
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 134.1,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.8214,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.8665,
        "column": 1.8716
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 42.8,
      "skirtDepthMm": 0
    },
    "groove": {
      "crownY": 1.7375,
      "crownT": 5.53,
      "crownScreen": {
        "waistUp": 1.7562,
        "column": 1.7635
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 37,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.7138,
      "crownT": 3.8,
      "crownScreen": {
        "waistUp": 1.7231,
        "column": 1.7296
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 44.5,
      "jumpDeg": 0.8,
      "skirtDepthMm": 0
    },
    "jumpAround": {
      "crownY": 2.0351,
      "crownT": 3.67,
      "crownScreen": {
        "waistUp": 2.0832,
        "column": 2.0855
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 142.7,
      "skirtDepthMm": 0
    },
    "macarena": {
      "crownY": 1.7282,
      "crownT": 8.03,
      "crownScreen": {
        "waistUp": 1.7415,
        "column": 1.742
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 17.9,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.711,
      "crownT": 0.53,
      "crownScreen": {
        "waistUp": 1.7107,
        "column": 1.7148
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 3.8,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.6824,
      "crownT": 1.13,
      "crownScreen": {
        "waistUp": 1.6868,
        "column": 1.6924
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 4,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.7184,
      "crownT": 0.1,
      "crownScreen": {
        "waistUp": 1.7251,
        "column": 1.7303
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 47.1,
      "jumpDeg": 2.8,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.7197,
      "crownT": 5.8,
      "crownScreen": {
        "waistUp": 1.7249,
        "column": 1.7291
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 4.1,
      "skirtDepthMm": 0
    },
    "shyPose": {
      "crownY": 1.7035,
      "crownT": 7.87,
      "crownScreen": {
        "waistUp": 1.7117,
        "column": 1.7187
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 12.1,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.731,
      "crownT": 2.13,
      "crownScreen": {
        "waistUp": 1.7421,
        "column": 1.7496
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 18,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.7292,
      "crownT": 8.2,
      "crownScreen": {
        "waistUp": 1.7256,
        "column": 1.728
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 20.5,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.942,
      "crownT": 1.67,
      "crownScreen": {
        "waistUp": 1.9504,
        "column": 1.9716
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 6.3,
      "skirtDepthMm": 0
    }
  }
}
