// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/mika-pink.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/avatar/springsim.ts public/avatar/mika-pink.vrm --clearance=src/components/chat/clearance/vroid-sample-b.pink.simulated.gen.ts --family=vroid-sample-b
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-sample-b",
  "rigSha": "e2aad79ec6667a5529934359339a6a08a29f73fe8a51f5cc6d4d702e137c1b45",
  "simulatedOn": "/avatar/mika-pink.vrm",
  "producedBy": "d89982b",
  "restCrownY": 1.582,
  "restCrownScreen": {
    "waistUp": 1.5707,
    "column": 1.5546
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "playFingers": {
        "column": 0.02
      },
      "scratchHead": {
        "column": 0.02
      },
      "dance": {
        "waistUp": -0.07,
        "column": 0.14
      },
      "groove": {
        "waistUp": -0.13,
        "column": 0.08
      },
      "macarena": {
        "waistUp": -0.22,
        "column": 0.03
      },
      "catwalk": {
        "column": 0.04
      },
      "jumpAround": {
        "waistUp": 0.13,
        "column": 0.38
      },
      "cheer": {
        "waistUp": -0.07,
        "column": 0.19
      },
      "shyPose": {
        "column": 0.03
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.5956,
      "crownT": 0.1,
      "crownScreen": {
        "waistUp": 1.5833,
        "column": 1.5657
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 28.1,
      "jumpDeg": 2.5,
      "skirtDepthMm": 0
    },
    "catwalk": {
      "crownY": 1.6059,
      "crownT": 7.27,
      "crownScreen": {
        "waistUp": 1.615,
        "column": 1.6323
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 15,
      "skirtDepthMm": 0
    },
    "cheer": {
      "crownY": 1.7313,
      "crownT": 1.97,
      "crownScreen": {
        "waistUp": 1.7712,
        "column": 1.7747
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 80.6,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.6614,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.7229,
        "column": 1.7374
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 26.8,
      "skirtDepthMm": 0
    },
    "groove": {
      "crownY": 1.6661,
      "crownT": 5.6,
      "crownScreen": {
        "waistUp": 1.6729,
        "column": 1.6747
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 21.1,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.5839,
      "crownT": 9.13,
      "crownScreen": {
        "waistUp": 1.5753,
        "column": 1.5634
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 20.9,
      "jumpDeg": 0.4,
      "skirtDepthMm": 0
    },
    "jumpAround": {
      "crownY": 1.9429,
      "crownT": 3.63,
      "crownScreen": {
        "waistUp": 1.9754,
        "column": 1.9781
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 129.7,
      "skirtDepthMm": 0
    },
    "macarena": {
      "crownY": 1.6309,
      "crownT": 8.07,
      "crownScreen": {
        "waistUp": 1.6283,
        "column": 1.6285
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 23.2,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.6002,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.5905,
        "column": 1.5846
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 2.6,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.5752,
      "crownT": 0.57,
      "crownScreen": {
        "waistUp": 1.5693,
        "column": 1.573
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 4.3,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.6283,
      "crownT": 4.37,
      "crownScreen": {
        "waistUp": 1.6205,
        "column": 1.6128
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 22.3,
      "jumpDeg": 2.4,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.6221,
      "crownT": 1.1,
      "crownScreen": {
        "waistUp": 1.617,
        "column": 1.6127
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 4.9,
      "skirtDepthMm": 0
    },
    "shyPose": {
      "crownY": 1.6229,
      "crownT": 4.43,
      "crownScreen": {
        "waistUp": 1.6199,
        "column": 1.6213
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 7.2,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.618,
      "crownT": 2.2,
      "crownScreen": {
        "waistUp": 1.6121,
        "column": 1.6182
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 16,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.5986,
      "crownT": 9.3,
      "crownScreen": {
        "waistUp": 1.5896,
        "column": 1.5777
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 6.6,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.8148,
      "crownT": 1.87,
      "crownScreen": {
        "waistUp": 1.8273,
        "column": 1.8429
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 26.1,
      "jumpDeg": 3.7,
      "skirtDepthMm": 0
    }
  }
}
