// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/mika-pink.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame. Regenerate:
//   npx tsx scripts/avatar/springsim.ts public/avatar/mika-pink.vrm --clearance=src/components/chat/clearance/vroid-sample-b.pink.simulated.gen.ts
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-sample-b",
  "rigSha": "e2aad79ec6667a5529934359339a6a08a29f73fe8a51f5cc6d4d702e137c1b45",
  "simulatedOn": "/avatar/mika-pink.vrm",
  "producedBy": "b49f6b6",
  "restCrownY": 1.582,
  "restCrownScreen": {
    "waistUp": 1.5707,
    "column": 1.5546
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "playFingers": {
        "column": 0.02
      },
      "scratchHead": {
        "column": 0.02
      },
      "dance": {
        "waistUp": -0.07,
        "column": 0.14
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.5956,
      "crownT": 0.1,
      "crownScreen": {
        "waistUp": 1.5833,
        "column": 1.5657
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 29.6,
      "jumpDeg": 2.5,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.6614,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.7229,
        "column": 1.7374
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 26.8,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.5839,
      "crownT": 9.13,
      "crownScreen": {
        "waistUp": 1.5753,
        "column": 1.5634
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 20.9,
      "jumpDeg": 0.4,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.6002,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.5905,
        "column": 1.5846
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 2.6,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.5752,
      "crownT": 0.57,
      "crownScreen": {
        "waistUp": 1.5693,
        "column": 1.573
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 4.3,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.6283,
      "crownT": 4.37,
      "crownScreen": {
        "waistUp": 1.6205,
        "column": 1.6128
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 22.3,
      "jumpDeg": 2.4,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.6221,
      "crownT": 1.1,
      "crownScreen": {
        "waistUp": 1.617,
        "column": 1.6127
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 4.9,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.618,
      "crownT": 2.2,
      "crownScreen": {
        "waistUp": 1.6121,
        "column": 1.6182
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 16,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.5986,
      "crownT": 9.3,
      "crownScreen": {
        "waistUp": 1.5896,
        "column": 1.5777
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 6.6,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.8148,
      "crownT": 1.87,
      "crownScreen": {
        "waistUp": 1.8273,
        "column": 1.8429
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 48.1,
      "jumpDeg": 3.7,
      "skirtDepthMm": 0
    }
  }
}
