// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/HairSample_Female_webp.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame. Regenerate:
//   npx tsx scripts/avatar/springsim.ts public/avatar/HairSample_Female_webp.vrm --clearance=src/components/chat/clearance/vroid-hair-female.simulated.gen.ts --family=vroid-hair-female
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-hair-female",
  "rigSha": "1fc70bda729034c1735b28553c930c59316d9740b1d7721957fcc74308d0ff91",
  "simulatedOn": "/avatar/HairSample_Female_webp.vrm",
  "producedBy": "cff0bea",
  "restCrownY": 1.6682,
  "restCrownScreen": {
    "waistUp": 1.6719,
    "column": 1.6786
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "peaceSign": {
        "column": 0.06
      },
      "modelPose": {
        "column": 0.08
      },
      "spin": {
        "column": 0.12
      },
      "squat": {
        "column": 0.09
      },
      "akimbo": {
        "column": 0.09
      },
      "playFingers": {
        "column": 0.09
      },
      "scratchHead": {
        "column": 0.09
      },
      "idleLoop": {
        "column": 0.09
      },
      "stretch": {
        "waistUp": 0.11
      },
      "dance": {
        "column": 0.23
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.6801,
      "crownT": 6.4,
      "crownScreen": {
        "waistUp": 1.6791,
        "column": 1.682
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 1.8,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.7793,
      "crownT": 12,
      "crownScreen": {
        "waistUp": 1.8174,
        "column": 1.8227
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 16.6,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.6708,
      "crownT": 8.83,
      "crownScreen": {
        "waistUp": 1.6794,
        "column": 1.6881
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 0.3,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.6697,
      "crownT": 0.87,
      "crownScreen": {
        "waistUp": 1.6723,
        "column": 1.6779
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 1.7,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.6427,
      "crownT": 1.1,
      "crownScreen": {
        "waistUp": 1.648,
        "column": 1.6581
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 1.9,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.6729,
      "crownT": 4.73,
      "crownScreen": {
        "waistUp": 1.6786,
        "column": 1.6855
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 1.5,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.6778,
      "crownT": 5.8,
      "crownScreen": {
        "waistUp": 1.6824,
        "column": 1.6875
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 1.6,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.6918,
      "crownT": 2.13,
      "crownScreen": {
        "waistUp": 1.7005,
        "column": 1.7136
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 13.6,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.6893,
      "crownT": 8.23,
      "crownScreen": {
        "waistUp": 1.6836,
        "column": 1.6836
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 2.9,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.8993,
      "crownT": 1.67,
      "crownScreen": {
        "waistUp": 1.9119,
        "column": 1.9386
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 3.1,
      "skirtDepthMm": 0
    }
  }
}
