// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/HairSample_Female_webp.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/measure-motions.ts public/avatar/HairSample_Female_webp.vrm --write src/components/chat/clearance/vroid-hair-female.measured.gen.ts --family=vroid-hair-female
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-hair-female",
  "rigSha": "1fc70bda729034c1735b28553c930c59316d9740b1d7721957fcc74308d0ff91",
  "measuredOn": "/avatar/HairSample_Female_webp.vrm",
  "producedBy": "d89982b",
  "faceBox": {
    "min": [
      -0.1079,
      1.3887,
      -0.1067
    ],
    "max": [
      0.1086,
      1.6208,
      0.0411
    ]
  },
  "handSkinPastTip": 0.0208,
  "restCrownY": 1.6682,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.6387,
        "right": 0.5022
      },
      "skinTop": 1.5349,
      "hipsLow": 0.8842,
      "faceRatio": 1.4857,
      "faceRatioAt": 9.45,
      "endSink": 0.0388,
      "hipsDrift": 0.0153,
      "endWrist": 0.8502
    },
    "modelPose": {
      "reach": {
        "left": 0.3729,
        "right": 0.3912
      },
      "skinTop": 1.3702,
      "hipsLow": 0.9234,
      "faceRatio": 9.8699,
      "faceRatioAt": 3.88,
      "endSink": 0.0089,
      "hipsDrift": 0.028,
      "endWrist": 0.896
    },
    "spin": {
      "reach": {
        "left": 0.7077,
        "right": 0.549
      },
      "skinTop": 1.5991,
      "hipsLow": 0.8922,
      "faceRatio": 4.745,
      "faceRatioAt": 2.43,
      "endSink": 0,
      "hipsDrift": 0.0137,
      "endWrist": 0.8956
    },
    "squat": {
      "reach": {
        "left": 0.6565,
        "right": 0.643
      },
      "skinTop": 1.4483,
      "hipsLow": 0.7095,
      "faceRatio": 1.6639,
      "faceRatioAt": 6.12,
      "endSink": 0,
      "hipsDrift": 0.011,
      "endWrist": 0.892
    },
    "akimbo": {
      "reach": {
        "left": 0.2894,
        "right": 0.3627
      },
      "skinTop": 1.0743,
      "hipsLow": 0.9477,
      "faceRatio": 16.0892,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8993
    },
    "playFingers": {
      "reach": {
        "left": 0.3077,
        "right": 0.3077
      },
      "skinTop": 1.1209,
      "hipsLow": 0.948,
      "faceRatio": 19.3909,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8993
    },
    "scratchHead": {
      "reach": {
        "left": 0.453,
        "right": 0.5434
      },
      "skinTop": 1.6797,
      "hipsLow": 0.9433,
      "faceRatio": 0.7604,
      "faceRatioAt": 4.3,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8993
    },
    "idleLoop": {
      "reach": {
        "left": 0.4085,
        "right": 0.0992
      },
      "skinTop": 0.8981,
      "hipsLow": 0.9417,
      "faceRatio": 31.6167,
      "faceRatioAt": 1.54,
      "endSink": 0.0016,
      "hipsDrift": 0.1635,
      "endWrist": 0.8845
    },
    "stretch": {
      "reach": {
        "left": 0.3827,
        "right": 0.5721
      },
      "skinTop": 1.9088,
      "hipsLow": 0.9485,
      "faceRatio": 2.4514,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8993
    },
    "dance": {
      "reach": {
        "left": 0.746,
        "right": 0.534
      },
      "skinTop": 1.5935,
      "hipsLow": 0.8089,
      "faceRatio": 0.1871,
      "faceRatioAt": 8.23,
      "endSink": 0.0506,
      "hipsDrift": 0.1507,
      "endWrist": 1.2716
    },
    "groove": {
      "reach": {
        "left": 0.4481,
        "right": 0.6036
      },
      "skinTop": 1.1488,
      "hipsLow": 0.7519,
      "faceRatio": 3.7246,
      "faceRatioAt": 1.53,
      "endSink": 0.0106,
      "hipsDrift": 0.0002,
      "endWrist": 0.8715
    },
    "macarena": {
      "reach": {
        "left": 0.4719,
        "right": 0.4224
      },
      "skinTop": 1.5619,
      "hipsLow": 0.619,
      "faceRatio": 0.2059,
      "faceRatioAt": 4.13,
      "endSink": 0.0741,
      "hipsDrift": 0.0021,
      "endWrist": 1.0693
    },
    "catwalk": {
      "reach": {
        "left": 0.5542,
        "right": 0.489
      },
      "skinTop": 1.2042,
      "hipsLow": 0.8785,
      "faceRatio": 13.6384,
      "faceRatioAt": 6.53,
      "endSink": 0.0378,
      "hipsDrift": 0.004,
      "endWrist": 0.9374
    },
    "jumpAround": {
      "reach": {
        "left": 0.5496,
        "right": 0.3495
      },
      "skinTop": 1.6039,
      "hipsLow": 0.8562,
      "faceRatio": 14.407,
      "faceRatioAt": 4.27,
      "endSink": 0.0106,
      "hipsDrift": 0.0002,
      "endWrist": 0.8715
    },
    "cheer": {
      "reach": {
        "left": 0.4199,
        "right": 0.5805
      },
      "skinTop": 1.8459,
      "hipsLow": 0.7276,
      "faceRatio": 2.3293,
      "faceRatioAt": 3.87,
      "endSink": 0.0106,
      "hipsDrift": 0.0002,
      "endWrist": 0.8715
    },
    "shyPose": {
      "reach": {
        "left": 0.4417,
        "right": 0.2864
      },
      "skinTop": 1.3291,
      "hipsLow": 0.8774,
      "faceRatio": 1.8493,
      "faceRatioAt": 2.43,
      "endSink": 0.0106,
      "hipsDrift": 0.0002,
      "endWrist": 0.8715
    }
  }
}
