// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/mika-glasses_webp-2.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/measure-motions.ts public/avatar/mika-glasses_webp-2.vrm --write src/components/chat/clearance/vroid-mika-glasses.measured.gen.ts --family=vroid-mika-glasses
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-mika-glasses",
  "rigSha": "d226731cb2298d6fc18d4cc7d4f6840b48131ccbc4da2b95fed7096e895853b5",
  "measuredOn": "/avatar/mika-glasses_webp-2.vrm",
  "producedBy": "d0e9d1b",
  "faceBox": {
    "min": [
      -0.1065,
      1.3312,
      -0.0873
    ],
    "max": [
      0.1065,
      1.5595,
      0.0544
    ]
  },
  "handSkinPastTip": 0.0193,
  "restCrownY": 1.582,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.6381,
        "right": 0.4966
      },
      "skinTop": 1.4671,
      "hipsLow": 0.8399,
      "faceRatio": 1.4982,
      "faceRatioAt": 9.45,
      "endSink": 0.0368,
      "hipsDrift": 0.0145,
      "endWrist": 0.8077
    },
    "modelPose": {
      "reach": {
        "left": 0.3921,
        "right": 0.361
      },
      "skinTop": 1.2876,
      "hipsLow": 0.8772,
      "faceRatio": 12.6717,
      "faceRatioAt": 3.95,
      "endSink": 0.0085,
      "hipsDrift": 0.0266,
      "endWrist": 0.8529
    },
    "spin": {
      "reach": {
        "left": 0.689,
        "right": 0.5422
      },
      "skinTop": 1.5107,
      "hipsLow": 0.8476,
      "faceRatio": 6.3797,
      "faceRatioAt": 2.45,
      "endSink": 0,
      "hipsDrift": 0.013,
      "endWrist": 0.8491
    },
    "squat": {
      "reach": {
        "left": 0.6519,
        "right": 0.6472
      },
      "skinTop": 1.4086,
      "hipsLow": 0.674,
      "faceRatio": 1.6796,
      "faceRatioAt": 6.07,
      "endSink": 0,
      "hipsDrift": 0.0104,
      "endWrist": 0.8464
    },
    "akimbo": {
      "reach": {
        "left": 0.305,
        "right": 0.3355
      },
      "skinTop": 1.0172,
      "hipsLow": 0.9003,
      "faceRatio": 16.9574,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8605
    },
    "playFingers": {
      "reach": {
        "left": 0.2909,
        "right": 0.2922
      },
      "skinTop": 1.0595,
      "hipsLow": 0.9005,
      "faceRatio": 20.1034,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8605
    },
    "scratchHead": {
      "reach": {
        "left": 0.4213,
        "right": 0.5386
      },
      "skinTop": 1.6118,
      "hipsLow": 0.8961,
      "faceRatio": 1.2478,
      "faceRatioAt": 4.32,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8605
    },
    "idleLoop": {
      "reach": {
        "left": 0.4058,
        "right": 0.1071
      },
      "skinTop": 0.8506,
      "hipsLow": 0.8946,
      "faceRatio": 31.4642,
      "faceRatioAt": 1.5,
      "endSink": 0.0015,
      "hipsDrift": 0.1553,
      "endWrist": 0.8386
    },
    "stretch": {
      "reach": {
        "left": 0.3565,
        "right": 0.5873
      },
      "skinTop": 1.8314,
      "hipsLow": 0.901,
      "faceRatio": 2.6615,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8605
    },
    "dance": {
      "reach": {
        "left": 0.7082,
        "right": 0.5492
      },
      "skinTop": 1.5289,
      "hipsLow": 0.7684,
      "faceRatio": 0.4058,
      "faceRatioAt": 8.23,
      "endSink": 0.048,
      "hipsDrift": 0.1431,
      "endWrist": 1.2169
    }
  }
}
