// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/Vita_webp.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown. Regenerate:
//   npx tsx scripts/measure-motions.ts public/avatar/Vita_webp.vrm --write src/components/chat/clearance/vroid-vita.measured.gen.ts --family=vroid-vita
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-vita",
  "rigSha": "7d04404f31887fd4d4f64032179ec1bbc3a99f11294bbc2635096714fb913702",
  "measuredOn": "/avatar/Vita_webp.vrm",
  "producedBy": "8f724ea",
  "faceBox": {
    "min": [
      -0.1073,
      1.4329,
      -0.1092
    ],
    "max": [
      0.1081,
      1.6666,
      0.0391
    ]
  },
  "handSkinPastTip": 0.0208,
  "restCrownY": 1.713,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.6401,
        "right": 0.5001
      },
      "skinTop": 1.5753,
      "hipsLow": 0.9206,
      "faceRatio": 1.4664,
      "faceRatioAt": 9.45,
      "endSink": 0.0404,
      "hipsDrift": 0.0159,
      "endWrist": 0.8907
    },
    "modelPose": {
      "reach": {
        "left": 0.4149,
        "right": 0.3929
      },
      "skinTop": 1.4115,
      "hipsLow": 0.9615,
      "faceRatio": 9.8778,
      "faceRatioAt": 3.88,
      "endSink": 0.0093,
      "hipsDrift": 0.0291,
      "endWrist": 0.9377
    },
    "spin": {
      "reach": {
        "left": 0.7106,
        "right": 0.5467
      },
      "skinTop": 1.6411,
      "hipsLow": 0.929,
      "faceRatio": 4.7656,
      "faceRatioAt": 2.43,
      "endSink": 0,
      "hipsDrift": 0.0143,
      "endWrist": 0.9379
    },
    "squat": {
      "reach": {
        "left": 0.6568,
        "right": 0.6432
      },
      "skinTop": 1.4908,
      "hipsLow": 0.7387,
      "faceRatio": 1.6922,
      "faceRatioAt": 6.12,
      "endSink": 0,
      "hipsDrift": 0.0114,
      "endWrist": 0.9343
    },
    "akimbo": {
      "reach": {
        "left": 0.289,
        "right": 0.3647
      },
      "skinTop": 1.1166,
      "hipsLow": 0.9868,
      "faceRatio": 16.1128,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.9416
    },
    "playFingers": {
      "reach": {
        "left": 0.3077,
        "right": 0.3078
      },
      "skinTop": 1.1632,
      "hipsLow": 0.9871,
      "faceRatio": 19.3093,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.9416
    },
    "scratchHead": {
      "reach": {
        "left": 0.4549,
        "right": 0.5424
      },
      "skinTop": 1.7217,
      "hipsLow": 0.9822,
      "faceRatio": 0.7116,
      "faceRatioAt": 4.3,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.9416
    },
    "idleLoop": {
      "reach": {
        "left": 0.4534,
        "right": 0.131
      },
      "skinTop": 0.9402,
      "hipsLow": 0.9806,
      "faceRatio": 31.4842,
      "faceRatioAt": 1.54,
      "endSink": 0.0017,
      "hipsDrift": 0.1703,
      "endWrist": 0.9265
    },
    "stretch": {
      "reach": {
        "left": 0.3832,
        "right": 0.5716
      },
      "skinTop": 1.9516,
      "hipsLow": 0.9876,
      "faceRatio": 2.4197,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.9416
    },
    "dance": {
      "reach": {
        "left": 0.7543,
        "right": 0.5494
      },
      "skinTop": 1.637,
      "hipsLow": 0.8422,
      "faceRatio": 0.1999,
      "faceRatioAt": 8.23,
      "endSink": 0.0527,
      "hipsDrift": 0.1569,
      "endWrist": 1.3117
    }
  }
}
