// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/gishin-2.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/avatar/springsim.ts public/avatar/gishin-2.vrm --clearance=src/components/chat/clearance/vroid-gishin.simulated.gen.ts --family=vroid-gishin
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-gishin",
  "rigSha": "c300afebc90f10a9b44e61a917a75721854d7126468b7f511ada55d70da9d351",
  "simulatedOn": "/avatar/gishin-2.vrm",
  "producedBy": "4b010f5",
  "restCrownY": 1.582,
  "restCrownScreen": {
    "waistUp": 1.5814,
    "column": 1.5859
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "spin": {
        "column": 0.03
      },
      "scratchHead": {
        "column": 0.04
      },
      "dance": {
        "column": 0.12
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.5869,
      "crownT": 10.1,
      "crownScreen": {
        "waistUp": 1.5861,
        "column": 1.5915
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 42.1,
      "jumpDeg": 2.8,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.6579,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.6842,
        "column": 1.7042
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 22,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.5827,
      "crownT": 5.37,
      "crownScreen": {
        "waistUp": 1.5847,
        "column": 1.5933
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 11.2,
      "jumpDeg": 0.4,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.581,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.5768,
        "column": 1.5766
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 3.9,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.5484,
      "crownT": 0.67,
      "crownScreen": {
        "waistUp": 1.549,
        "column": 1.5561
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 2.5,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.5895,
      "crownT": 0.37,
      "crownScreen": {
        "waistUp": 1.589,
        "column": 1.5931
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 11.1,
      "jumpDeg": 1.8,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.6297,
      "crownT": 0.7,
      "crownScreen": {
        "waistUp": 1.63,
        "column": 1.6332
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 46,
      "jumpDeg": 3.1,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.593,
      "crownT": 6.83,
      "crownScreen": {
        "waistUp": 1.5983,
        "column": 1.6284
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 15.3,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.5956,
      "crownT": 8.17,
      "crownScreen": {
        "waistUp": 1.5921,
        "column": 1.5923
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 4.5,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.8425,
      "crownT": 1.6,
      "crownScreen": {
        "waistUp": 1.8517,
        "column": 1.864
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 4.5,
      "skirtDepthMm": 0
    },
    "waveWink": {
      "crownY": 1.582,
      "crownT": 0,
      "crownScreen": {
        "waistUp": 1.5814,
        "column": 1.5859
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 4.9,
      "jumpDeg": 0,
      "skirtDepthMm": 0
    }
  }
}
