// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/Sakurada_Fumiriya_webp.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame. Regenerate:
//   npx tsx scripts/avatar/springsim.ts public/avatar/Sakurada_Fumiriya_webp.vrm --clearance=src/components/chat/clearance/vroid-sakurada-fumiriya.simulated.gen.ts --family=vroid-sakurada-fumiriya
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-sakurada-fumiriya",
  "rigSha": "513b2ce73d3c278c1c20d7ce959bc77d3ce6f1bf834ab99275052c86bca69bc8",
  "simulatedOn": "/avatar/Sakurada_Fumiriya_webp.vrm",
  "producedBy": "1602992",
  "restCrownY": 1.9216,
  "restCrownScreen": {
    "waistUp": 1.9341,
    "column": 1.955
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "peaceSign": {
        "waistUp": 0.16,
        "column": 0.3
      },
      "modelPose": {
        "waistUp": 0.2,
        "column": 0.32
      },
      "spin": {
        "waistUp": 0.21,
        "column": 0.38
      },
      "squat": {
        "column": 0.34
      },
      "akimbo": {
        "waistUp": 0.22,
        "column": 0.34
      },
      "playFingers": {
        "waistUp": 0.23,
        "column": 0.34
      },
      "scratchHead": {
        "waistUp": 0.24,
        "column": 0.38
      },
      "idleLoop": {
        "waistUp": 0.22,
        "column": 0.34
      },
      "stretch": {
        "waistUp": 0.37
      },
      "dance": {
        "column": 0.51
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.9276,
      "crownT": 0.13,
      "crownScreen": {
        "waistUp": 1.9307,
        "column": 1.9352
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 47,
      "jumpDeg": 4.4,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 2.0179,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 2.1017,
        "column": 2.0664
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 43.5,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.9206,
      "crownT": 5.37,
      "crownScreen": {
        "waistUp": 1.928,
        "column": 1.9342
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 47.1,
      "jumpDeg": 0.6,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.9151,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.913,
        "column": 1.9182
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 3.9,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.877,
      "crownT": 0.63,
      "crownScreen": {
        "waistUp": 1.8857,
        "column": 1.8917
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 48.6,
      "jumpDeg": 3.3,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.929,
      "crownT": 4.63,
      "crownScreen": {
        "waistUp": 1.9333,
        "column": 1.9385
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 47.1,
      "jumpDeg": 2.1,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.9645,
      "crownT": 0.67,
      "crownScreen": {
        "waistUp": 1.9726,
        "column": 1.9782
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 48.6,
      "jumpDeg": 5.5,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.9278,
      "crownT": 6.83,
      "crownScreen": {
        "waistUp": 1.9468,
        "column": 1.9803
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.8,
      "jumpDeg": 15.9,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.9353,
      "crownT": 8.2,
      "crownScreen": {
        "waistUp": 1.9406,
        "column": 1.937
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.3,
      "jumpDeg": 12.7,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 2.2132,
      "crownT": 1.67,
      "crownScreen": {
        "waistUp": 2.2265,
        "column": 2.2694
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 47.4,
      "jumpDeg": 4.6,
      "skirtDepthMm": 0
    }
  }
}
