// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/mika-glasses_webp.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/avatar/springsim.ts public/avatar/mika-glasses_webp.vrm --clearance=src/components/chat/clearance/vroid-mika-glasses.simulated.gen.ts --family=vroid-mika-glasses
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-mika-glasses",
  "rigSha": "5a4a71392fcda5eb5e40d5adb3e4a5ca692c335d1eedb9caec15f85113cdee8c",
  "simulatedOn": "/avatar/mika-glasses_webp.vrm",
  "producedBy": "a7d4c4b",
  "restCrownY": 1.6172,
  "restCrownScreen": {
    "waistUp": 1.6175,
    "column": 1.6203
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "modelPose": {
        "column": 0.02
      },
      "spin": {
        "column": 0.06
      },
      "squat": {
        "column": 0.03
      },
      "akimbo": {
        "column": 0.03
      },
      "playFingers": {
        "column": 0.03
      },
      "scratchHead": {
        "column": 0.07
      },
      "idleLoop": {
        "column": 0.03
      },
      "stretch": {
        "waistUp": 0.08
      },
      "dance": {
        "column": 0.16
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.6224,
      "crownT": 10.07,
      "crownScreen": {
        "waistUp": 1.6224,
        "column": 1.6256
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.5,
      "jumpDeg": 2.7,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.6974,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.7385,
        "column": 1.7568
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 27.1,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.6182,
      "crownT": 5.37,
      "crownScreen": {
        "waistUp": 1.6215,
        "column": 1.6279
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 6.6,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.614,
      "crownT": 0.53,
      "crownScreen": {
        "waistUp": 1.6107,
        "column": 1.6128
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.5,
      "jumpDeg": 4.5,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.5823,
      "crownT": 0.1,
      "crownScreen": {
        "waistUp": 1.5849,
        "column": 1.592
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 8.3,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.6239,
      "crownT": 3.73,
      "crownScreen": {
        "waistUp": 1.624,
        "column": 1.6293
      },
      "coatDepthMm": 0,
      "bodyDepthMm": -50,
      "jumpDeg": 0.4,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.6584,
      "crownT": 0.7,
      "crownScreen": {
        "waistUp": 1.6589,
        "column": 1.6618
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 2.9,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.6304,
      "crownT": 6.83,
      "crownScreen": {
        "waistUp": 1.634,
        "column": 1.6565
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 48.3,
      "jumpDeg": 19.9,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.6318,
      "crownT": 8.17,
      "crownScreen": {
        "waistUp": 1.6257,
        "column": 1.6257
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 6.5,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.8749,
      "crownT": 1.6,
      "crownScreen": {
        "waistUp": 1.8824,
        "column": 1.8983
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.7,
      "jumpDeg": 2.2,
      "skirtDepthMm": 0
    }
  }
}
