// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/AvatarSample_A_webp.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame. Regenerate:
//   npx tsx scripts/avatar/springsim.ts public/avatar/AvatarSample_A_webp.vrm --clearance=src/components/chat/clearance/vroid-sample-a.simulated.gen.ts --family=vroid-sample-a
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-sample-a",
  "rigSha": "e1a17d2f3e50d140cd31acb423888e886017e4deb0c3d788a489cb4b4919b6a9",
  "simulatedOn": "/avatar/AvatarSample_A_webp.vrm",
  "producedBy": "1602992",
  "restCrownY": 1.5582,
  "restCrownScreen": {
    "waistUp": 1.5595,
    "column": 1.5652
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "spin": {
        "column": 0.03
      },
      "scratchHead": {
        "column": 0.01
      },
      "dance": {
        "column": 0.08
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.5631,
      "crownT": 10.1,
      "crownScreen": {
        "waistUp": 1.5641,
        "column": 1.5701
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 3,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.6332,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.6533,
        "column": 1.6757
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 29.1,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.5587,
      "crownT": 4.57,
      "crownScreen": {
        "waistUp": 1.5616,
        "column": 1.5706
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 0.4,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.5566,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.5534,
        "column": 1.5569
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 2.6,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.5236,
      "crownT": 0.7,
      "crownScreen": {
        "waistUp": 1.5256,
        "column": 1.5349
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 1.8,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.5651,
      "crownT": 0.37,
      "crownScreen": {
        "waistUp": 1.5655,
        "column": 1.5724
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 1.7,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.598,
      "crownT": 0.67,
      "crownScreen": {
        "waistUp": 1.6004,
        "column": 1.6063
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 3.9,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.5675,
      "crownT": 6.83,
      "crownScreen": {
        "waistUp": 1.5727,
        "column": 1.6227
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 16.3,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.5725,
      "crownT": 8.2,
      "crownScreen": {
        "waistUp": 1.5695,
        "column": 1.5708
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 3.7,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.8462,
      "crownT": 1.8,
      "crownScreen": {
        "waistUp": 1.8573,
        "column": 1.8715
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 6.5,
      "skirtDepthMm": 0
    }
  }
}
