// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/Sendagaya_Shibu_webp.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame. Regenerate:
//   npx tsx scripts/avatar/springsim.ts public/avatar/Sendagaya_Shibu_webp.vrm --clearance=src/components/chat/clearance/vroid-sendagaya-shibu.simulated.gen.ts --family=vroid-sendagaya-shibu
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-sendagaya-shibu",
  "rigSha": "2aca6c97393bdd8a09bc2039e3544dd02828f790bb3dcbd8fded52156d2e278a",
  "simulatedOn": "/avatar/Sendagaya_Shibu_webp.vrm",
  "producedBy": "cff0bea",
  "restCrownY": 1.6158,
  "restCrownScreen": {
    "waistUp": 1.6162,
    "column": 1.6222
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "modelPose": {
        "column": 0.02
      },
      "spin": {
        "column": 0.06
      },
      "squat": {
        "column": 0.03
      },
      "akimbo": {
        "column": 0.03
      },
      "playFingers": {
        "column": 0.03
      },
      "scratchHead": {
        "column": 0.05
      },
      "idleLoop": {
        "column": 0.03
      },
      "stretch": {
        "waistUp": 0.07
      },
      "dance": {
        "column": 0.14
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.6207,
      "crownT": 10.1,
      "crownScreen": {
        "waistUp": 1.6209,
        "column": 1.6265
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 3.2,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.6909,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.7209,
        "column": 1.7384
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 35.2,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.6163,
      "crownT": 5.37,
      "crownScreen": {
        "waistUp": 1.6196,
        "column": 1.6281
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 32.2,
      "jumpDeg": 0.6,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.6145,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.6108,
        "column": 1.6139
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 3.7,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.5813,
      "crownT": 0.67,
      "crownScreen": {
        "waistUp": 1.5834,
        "column": 1.592
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 2,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.6229,
      "crownT": 4.53,
      "crownScreen": {
        "waistUp": 1.6241,
        "column": 1.6297
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 35.1,
      "jumpDeg": 1.6,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.6337,
      "crownT": 0.67,
      "crownScreen": {
        "waistUp": 1.6369,
        "column": 1.6424
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 3.2,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.6261,
      "crownT": 6.83,
      "crownScreen": {
        "waistUp": 1.6345,
        "column": 1.6569
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 17.4,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.6288,
      "crownT": 8.17,
      "crownScreen": {
        "waistUp": 1.6249,
        "column": 1.6272
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 8.2,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.8643,
      "crownT": 1.67,
      "crownScreen": {
        "waistUp": 1.8724,
        "column": 1.8887
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 4,
      "skirtDepthMm": 0
    }
  }
}
