// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/AvatarSample_C_webp.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown. Regenerate:
//   npx tsx scripts/measure-motions.ts public/avatar/AvatarSample_C_webp.vrm --write src/components/chat/clearance/vroid-sample-c.measured.gen.ts --family=vroid-sample-c
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-sample-c",
  "rigSha": "6c651594cc59fb032affe7ea165d0562115632aa863b3ea12069cb713e2bc961",
  "measuredOn": "/avatar/AvatarSample_C_webp.vrm",
  "producedBy": "8f724ea",
  "faceBox": {
    "min": [
      -0.0976,
      1.5055,
      -0.1244
    ],
    "max": [
      0.0987,
      1.734,
      0.0151
    ]
  },
  "handSkinPastTip": 0.0231,
  "restCrownY": 1.7561,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.7311,
        "right": 0.5754
      },
      "skinTop": 1.7031,
      "hipsLow": 0.9538,
      "faceRatio": 1.3989,
      "faceRatioAt": 9.78,
      "endSink": 0.0418,
      "hipsDrift": 0.0165,
      "endWrist": 0.8812
    },
    "modelPose": {
      "reach": {
        "left": 0.4344,
        "right": 0.4045
      },
      "skinTop": 1.5137,
      "hipsLow": 0.9961,
      "faceRatio": 14.1759,
      "faceRatioAt": 3.88,
      "endSink": 0.0096,
      "hipsDrift": 0.0302,
      "endWrist": 0.9257
    },
    "spin": {
      "reach": {
        "left": 0.8094,
        "right": 0.6278
      },
      "skinTop": 1.7601,
      "hipsLow": 0.9625,
      "faceRatio": 5.3198,
      "faceRatioAt": 2.43,
      "endSink": 0,
      "hipsDrift": 0.0148,
      "endWrist": 0.9265
    },
    "squat": {
      "reach": {
        "left": 0.7515,
        "right": 0.7393
      },
      "skinTop": 1.5896,
      "hipsLow": 0.7654,
      "faceRatio": 1.8194,
      "faceRatioAt": 6.12,
      "endSink": 0,
      "hipsDrift": 0.0118,
      "endWrist": 0.9208
    },
    "akimbo": {
      "reach": {
        "left": 0.3376,
        "right": 0.4004
      },
      "skinTop": 1.1235,
      "hipsLow": 1.0224,
      "faceRatio": 21.158,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.9339
    },
    "playFingers": {
      "reach": {
        "left": 0.3288,
        "right": 0.3306
      },
      "skinTop": 1.1992,
      "hipsLow": 1.0226,
      "faceRatio": 26.749,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.9339
    },
    "scratchHead": {
      "reach": {
        "left": 0.4752,
        "right": 0.6278
      },
      "skinTop": 1.8585,
      "hipsLow": 1.0176,
      "faceRatio": 1.153,
      "faceRatioAt": 4.4,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.9339
    },
    "idleLoop": {
      "reach": {
        "left": 0.4583,
        "right": 0.1111
      },
      "skinTop": 0.9305,
      "hipsLow": 1.0159,
      "faceRatio": 42.3893,
      "faceRatioAt": 1.5,
      "endSink": 0.0017,
      "hipsDrift": 0.1764,
      "endWrist": 0.9169
    },
    "stretch": {
      "reach": {
        "left": 0.3875,
        "right": 0.6619
      },
      "skinTop": 2.095,
      "hipsLow": 1.0232,
      "faceRatio": 2.0944,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.9339
    },
    "dance": {
      "reach": {
        "left": 0.8455,
        "right": 0.6424
      },
      "skinTop": 1.7605,
      "hipsLow": 0.8726,
      "faceRatio": 0.0095,
      "faceRatioAt": 8.23,
      "endSink": 0.0546,
      "hipsDrift": 0.1625,
      "endWrist": 1.4194
    }
  }
}
