// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/vroid-studio-dressup.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame. Regenerate:
//   npx tsx scripts/avatar/springsim.ts public/avatar/vroid-studio-dressup.vrm --clearance=src/components/chat/clearance/vroid-studio-dressup.simulated.gen.ts --family=vroid-studio-dressup
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-studio-dressup",
  "rigSha": "ec3b9ab3648bcaea26792c0324d32f7fabda1245a58813a0139af5c00032491e",
  "simulatedOn": "/avatar/vroid-studio-dressup.vrm",
  "producedBy": "0c4607f",
  "rigidHair": true,
  "restCrownY": 1.5982,
  "restCrownScreen": {
    "waistUp": 1.5971,
    "column": 1.5994
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "spin": {
        "column": 0.04
      },
      "squat": {
        "column": 0.01
      },
      "akimbo": {
        "column": 0.01
      },
      "playFingers": {
        "column": 0.01
      },
      "scratchHead": {
        "column": 0.06
      },
      "idleLoop": {
        "column": 0.01
      },
      "stretch": {
        "waistUp": 0.07
      },
      "dance": {
        "column": 0.12
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.6029,
      "crownT": 10.2,
      "crownScreen": {
        "waistUp": 1.6019,
        "column": 1.6049
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 16.2,
      "jumpDeg": 0,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.6717,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.7008,
        "column": 1.7211
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 24,
      "jumpDeg": 0,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.599,
      "crownT": 5.37,
      "crownScreen": {
        "waistUp": 1.6004,
        "column": 1.6063
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 15.9,
      "jumpDeg": 0,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.5948,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.5903,
        "column": 1.588
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 16.8,
      "jumpDeg": 0,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.5635,
      "crownT": 0.67,
      "crownScreen": {
        "waistUp": 1.5648,
        "column": 1.5709
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 16.2,
      "jumpDeg": 0,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.6048,
      "crownT": 4.57,
      "crownScreen": {
        "waistUp": 1.6048,
        "column": 1.609
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 16.4,
      "jumpDeg": 0,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.6497,
      "crownT": 0.7,
      "crownScreen": {
        "waistUp": 1.6502,
        "column": 1.6531
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 16.2,
      "jumpDeg": 0,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.6068,
      "crownT": 6.83,
      "crownScreen": {
        "waistUp": 1.6125,
        "column": 1.6316
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 18.3,
      "jumpDeg": 0,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.6102,
      "crownT": 8.17,
      "crownScreen": {
        "waistUp": 1.6043,
        "column": 1.603
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 23.9,
      "jumpDeg": 0,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.8661,
      "crownT": 1.6,
      "crownScreen": {
        "waistUp": 1.8736,
        "column": 1.8889
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 18.6,
      "jumpDeg": 0,
      "skirtDepthMm": 0
    }
  }
}
