// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/rosa_webp.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/avatar/springsim.ts public/avatar/rosa_webp.vrm --clearance=src/components/chat/clearance/vroid-rosa.simulated.gen.ts --family=vroid-rosa
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-rosa",
  "rigSha": "2b28267463fb7132298616501791cd35261e5fbb1371421ff8648c4ee0782ec7",
  "simulatedOn": "/avatar/rosa_webp.vrm",
  "producedBy": "50ff87b",
  "restCrownY": 1.582,
  "restCrownScreen": {
    "waistUp": 1.5814,
    "column": 1.5866
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "spin": {
        "column": 0.03
      },
      "scratchHead": {
        "column": 0.03
      },
      "dance": {
        "waistUp": -0.08,
        "column": 0.12
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.5869,
      "crownT": 10.1,
      "crownScreen": {
        "waistUp": 1.5861,
        "column": 1.5922
      },
      "coatDepthMm": 0,
      "bodyDepthMm": -50,
      "jumpDeg": 2.7,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.6582,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.6932,
        "column": 1.7032
      },
      "coatDepthMm": 0,
      "bodyDepthMm": -50,
      "jumpDeg": 26.9,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.5827,
      "crownT": 5.37,
      "crownScreen": {
        "waistUp": 1.5847,
        "column": 1.5944
      },
      "coatDepthMm": 0,
      "bodyDepthMm": -50,
      "jumpDeg": 6.4,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.5809,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.5766,
        "column": 1.5765
      },
      "coatDepthMm": 0,
      "bodyDepthMm": -50,
      "jumpDeg": 4.5,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.5486,
      "crownT": 0.67,
      "crownScreen": {
        "waistUp": 1.5492,
        "column": 1.5566
      },
      "coatDepthMm": 0,
      "bodyDepthMm": -50,
      "jumpDeg": 8.2,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.5895,
      "crownT": 0.37,
      "crownScreen": {
        "waistUp": 1.5889,
        "column": 1.5932
      },
      "coatDepthMm": 0,
      "bodyDepthMm": -50,
      "jumpDeg": 0.4,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.6194,
      "crownT": 0.7,
      "crownScreen": {
        "waistUp": 1.6196,
        "column": 1.6229
      },
      "coatDepthMm": 0,
      "bodyDepthMm": -50,
      "jumpDeg": 2.9,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.5929,
      "crownT": 6.83,
      "crownScreen": {
        "waistUp": 1.5982,
        "column": 1.6151
      },
      "coatDepthMm": 0,
      "bodyDepthMm": -50,
      "jumpDeg": 19.9,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.5958,
      "crownT": 8.2,
      "crownScreen": {
        "waistUp": 1.5929,
        "column": 1.5938
      },
      "coatDepthMm": 0,
      "bodyDepthMm": -50,
      "jumpDeg": 6.4,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.8309,
      "crownT": 1.6,
      "crownScreen": {
        "waistUp": 1.8396,
        "column": 1.8517
      },
      "coatDepthMm": 0,
      "bodyDepthMm": -50,
      "jumpDeg": 2.2,
      "skirtDepthMm": 0
    }
  }
}
