// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/Sakurada_Fumiriya_webp.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown. Regenerate:
//   npx tsx scripts/measure-motions.ts public/avatar/Sakurada_Fumiriya_webp.vrm --write src/components/chat/clearance/vroid-sakurada-fumiriya.measured.gen.ts --family=vroid-sakurada-fumiriya
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-sakurada-fumiriya",
  "rigSha": "513b2ce73d3c278c1c20d7ce959bc77d3ce6f1bf834ab99275052c86bca69bc8",
  "measuredOn": "/avatar/Sakurada_Fumiriya_webp.vrm",
  "producedBy": "8f724ea",
  "faceBox": {
    "min": [
      -0.107,
      1.6368,
      -0.1258
    ],
    "max": [
      0.1085,
      1.8721,
      0.0182
    ]
  },
  "handSkinPastTip": 0.0231,
  "restCrownY": 1.9216,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.7305,
        "right": 0.5661
      },
      "skinTop": 1.8107,
      "hipsLow": 1.0743,
      "faceRatio": 1.4806,
      "faceRatioAt": 9.45,
      "endSink": 0.0471,
      "hipsDrift": 0.0186,
      "endWrist": 1.043
    },
    "modelPose": {
      "reach": {
        "left": 0.4338,
        "right": 0.3897
      },
      "skinTop": 1.6279,
      "hipsLow": 1.122,
      "faceRatio": 12.6422,
      "faceRatioAt": 3.88,
      "endSink": 0.0108,
      "hipsDrift": 0.034,
      "endWrist": 1.0885
    },
    "spin": {
      "reach": {
        "left": 0.8091,
        "right": 0.6118
      },
      "skinTop": 1.8742,
      "hipsLow": 1.0841,
      "faceRatio": 4.5866,
      "faceRatioAt": 2.43,
      "endSink": 0,
      "hipsDrift": 0.0166,
      "endWrist": 1.0914
    },
    "squat": {
      "reach": {
        "left": 0.7421,
        "right": 0.7291
      },
      "skinTop": 1.7116,
      "hipsLow": 0.8621,
      "faceRatio": 1.1351,
      "faceRatioAt": 6.1,
      "endSink": 0,
      "hipsDrift": 0.0133,
      "endWrist": 1.0846
    },
    "akimbo": {
      "reach": {
        "left": 0.3408,
        "right": 0.3905
      },
      "skinTop": 1.2853,
      "hipsLow": 1.1515,
      "faceRatio": 18.507,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0008,
      "endWrist": 1.1025
    },
    "playFingers": {
      "reach": {
        "left": 0.3306,
        "right": 0.3323
      },
      "skinTop": 1.3467,
      "hipsLow": 1.1518,
      "faceRatio": 22.4387,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0008,
      "endWrist": 1.1025
    },
    "scratchHead": {
      "reach": {
        "left": 0.4628,
        "right": 0.6188
      },
      "skinTop": 1.9761,
      "hipsLow": 1.1461,
      "faceRatio": 1.068,
      "faceRatioAt": 4.3,
      "endSink": 0,
      "hipsDrift": 0.0008,
      "endWrist": 1.1025
    },
    "idleLoop": {
      "reach": {
        "left": 0.4767,
        "right": 0.0852
      },
      "skinTop": 1.0961,
      "hipsLow": 1.1442,
      "faceRatio": 36.9752,
      "faceRatioAt": 1.54,
      "endSink": 0.0019,
      "hipsDrift": 0.1987,
      "endWrist": 1.0826
    },
    "stretch": {
      "reach": {
        "left": 0.3951,
        "right": 0.6552
      },
      "skinTop": 2.2226,
      "hipsLow": 1.1524,
      "faceRatio": 2.5686,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0008,
      "endWrist": 1.1025
    },
    "dance": {
      "reach": {
        "left": 0.8679,
        "right": 0.6571
      },
      "skinTop": 1.8732,
      "hipsLow": 0.9828,
      "faceRatio": 0.1873,
      "faceRatioAt": 8.23,
      "endSink": 0.0615,
      "hipsDrift": 0.1831,
      "endWrist": 1.5211
    }
  }
}
