// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/mika-glasses_webp.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/measure-motions.ts public/avatar/mika-glasses_webp.vrm --write src/components/chat/clearance/vroid-mika-glasses.measured.gen.ts --family=vroid-mika-glasses
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-mika-glasses",
  "rigSha": "5a4a71392fcda5eb5e40d5adb3e4a5ca692c335d1eedb9caec15f85113cdee8c",
  "measuredOn": "/avatar/mika-glasses_webp.vrm",
  "producedBy": "a7d4c4b",
  "faceBox": {
    "min": [
      -0.1088,
      1.3608,
      -0.0893
    ],
    "max": [
      0.1088,
      1.5942,
      0.0556
    ]
  },
  "handSkinPastTip": 0.0197,
  "restCrownY": 1.6172,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.6523,
        "right": 0.5076
      },
      "skinTop": 1.4995,
      "hipsLow": 0.8586,
      "faceRatio": 1.4982,
      "faceRatioAt": 9.45,
      "endSink": 0.0377,
      "hipsDrift": 0.0149,
      "endWrist": 0.8256
    },
    "modelPose": {
      "reach": {
        "left": 0.4009,
        "right": 0.3691
      },
      "skinTop": 1.316,
      "hipsLow": 0.8967,
      "faceRatio": 12.6717,
      "faceRatioAt": 3.95,
      "endSink": 0.0086,
      "hipsDrift": 0.0271,
      "endWrist": 0.8718
    },
    "spin": {
      "reach": {
        "left": 0.7043,
        "right": 0.5543
      },
      "skinTop": 1.544,
      "hipsLow": 0.8664,
      "faceRatio": 6.3797,
      "faceRatioAt": 2.45,
      "endSink": 0,
      "hipsDrift": 0.0133,
      "endWrist": 0.868
    },
    "squat": {
      "reach": {
        "left": 0.6664,
        "right": 0.6616
      },
      "skinTop": 1.4397,
      "hipsLow": 0.689,
      "faceRatio": 1.6796,
      "faceRatioAt": 6.07,
      "endSink": 0,
      "hipsDrift": 0.0107,
      "endWrist": 0.8652
    },
    "akimbo": {
      "reach": {
        "left": 0.3118,
        "right": 0.3429
      },
      "skinTop": 1.0396,
      "hipsLow": 0.9203,
      "faceRatio": 16.9574,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8797
    },
    "playFingers": {
      "reach": {
        "left": 0.2973,
        "right": 0.2987
      },
      "skinTop": 1.0828,
      "hipsLow": 0.9206,
      "faceRatio": 20.1034,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8797
    },
    "scratchHead": {
      "reach": {
        "left": 0.4307,
        "right": 0.5505
      },
      "skinTop": 1.6474,
      "hipsLow": 0.916,
      "faceRatio": 1.2478,
      "faceRatioAt": 4.32,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8797
    },
    "idleLoop": {
      "reach": {
        "left": 0.4149,
        "right": 0.1095
      },
      "skinTop": 0.8692,
      "hipsLow": 0.9145,
      "faceRatio": 31.4642,
      "faceRatioAt": 1.5,
      "endSink": 0.0016,
      "hipsDrift": 0.1588,
      "endWrist": 0.8572
    },
    "stretch": {
      "reach": {
        "left": 0.3644,
        "right": 0.6003
      },
      "skinTop": 1.8719,
      "hipsLow": 0.921,
      "faceRatio": 2.6615,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8797
    },
    "dance": {
      "reach": {
        "left": 0.7239,
        "right": 0.5615
      },
      "skinTop": 1.5627,
      "hipsLow": 0.7855,
      "faceRatio": 0.4058,
      "faceRatioAt": 8.23,
      "endSink": 0.0491,
      "hipsDrift": 0.1463,
      "endWrist": 1.244
    }
  }
}
