// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/HairSample_Male_webp.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/avatar/springsim.ts public/avatar/HairSample_Male_webp.vrm --clearance=src/components/chat/clearance/vroid-hair-male.simulated.gen.ts --family=vroid-hair-male
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-hair-male",
  "rigSha": "8d88e224dc7943803f54f2e84dae2f1383426089b5369a292b4a94423a5f9e49",
  "simulatedOn": "/avatar/HairSample_Male_webp.vrm",
  "producedBy": "d89982b",
  "restCrownY": 1.8067,
  "restCrownScreen": {
    "waistUp": 1.8173,
    "column": 1.828
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "peaceSign": {
        "column": 0.19
      },
      "modelPose": {
        "column": 0.21
      },
      "spin": {
        "column": 0.25
      },
      "squat": {
        "column": 0.22
      },
      "akimbo": {
        "column": 0.23
      },
      "playFingers": {
        "column": 0.23
      },
      "scratchHead": {
        "column": 0.24
      },
      "idleLoop": {
        "column": 0.23
      },
      "stretch": {
        "waistUp": 0.23
      },
      "dance": {
        "waistUp": 0.08,
        "column": 0.34
      },
      "groove": {
        "column": 0.24
      },
      "macarena": {
        "waistUp": -0.02,
        "column": 0.23
      },
      "catwalk": {
        "column": 0.22
      },
      "jumpAround": {
        "waistUp": 0.32,
        "column": 0.57
      },
      "cheer": {
        "waistUp": 0.2,
        "column": 0.46
      },
      "shyPose": {
        "column": 0.23
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.8122,
      "crownT": 0.27,
      "crownScreen": {
        "waistUp": 1.8225,
        "column": 1.8242
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 42,
      "jumpDeg": 2.1,
      "skirtDepthMm": 0
    },
    "catwalk": {
      "crownY": 1.7946,
      "crownT": 3.8,
      "crownScreen": {
        "waistUp": 1.8072,
        "column": 1.8117
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 7.8,
      "skirtDepthMm": 0
    },
    "cheer": {
      "crownY": 1.9924,
      "crownT": 1.97,
      "crownScreen": {
        "waistUp": 2.0462,
        "column": 2.0502
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.7,
      "jumpDeg": 60,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.8899,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.9354,
        "column": 1.9374
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 18.3,
      "skirtDepthMm": 0
    },
    "groove": {
      "crownY": 1.8016,
      "crownT": 0.73,
      "crownScreen": {
        "waistUp": 1.8279,
        "column": 1.8307
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 17.4,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.8063,
      "crownT": 5.1,
      "crownScreen": {
        "waistUp": 1.8226,
        "column": 1.825
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 41.8,
      "jumpDeg": 0.3,
      "skirtDepthMm": 0
    },
    "jumpAround": {
      "crownY": 2.1154,
      "crownT": 2.7,
      "crownScreen": {
        "waistUp": 2.1652,
        "column": 2.169
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.3,
      "jumpDeg": 82.3,
      "skirtDepthMm": 0
    },
    "macarena": {
      "crownY": 1.8009,
      "crownT": 8.07,
      "crownScreen": {
        "waistUp": 1.8284,
        "column": 1.8304
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 7.3,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.7965,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.8034,
        "column": 1.8065
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 44.8,
      "jumpDeg": 1.6,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.7652,
      "crownT": 0.73,
      "crownScreen": {
        "waistUp": 1.781,
        "column": 1.7857
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 1.5,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.8118,
      "crownT": 0.07,
      "crownScreen": {
        "waistUp": 1.8245,
        "column": 1.8265
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 20.1,
      "jumpDeg": 1.1,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.8257,
      "crownT": 0.67,
      "crownScreen": {
        "waistUp": 1.8381,
        "column": 1.8396
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.8,
      "jumpDeg": 1.9,
      "skirtDepthMm": 0
    },
    "shyPose": {
      "crownY": 1.7928,
      "crownT": 7.93,
      "crownScreen": {
        "waistUp": 1.8114,
        "column": 1.8141
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 6.1,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.807,
      "crownT": 0.23,
      "crownScreen": {
        "waistUp": 1.841,
        "column": 1.8437
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 46.5,
      "jumpDeg": 13.9,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.8235,
      "crownT": 8.23,
      "crownScreen": {
        "waistUp": 1.819,
        "column": 1.82
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 47,
      "jumpDeg": 3.3,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 2.0724,
      "crownT": 1.67,
      "crownScreen": {
        "waistUp": 2.0846,
        "column": 2.1149
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 41.7,
      "jumpDeg": 2.7,
      "skirtDepthMm": 0
    }
  }
}
