// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/Sendagaya_Shibu_webp.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown. Regenerate:
//   npx tsx scripts/measure-motions.ts public/avatar/Sendagaya_Shibu_webp.vrm --write src/components/chat/clearance/vroid-sendagaya-shibu.measured.gen.ts --family=vroid-sendagaya-shibu
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-sendagaya-shibu",
  "rigSha": "2aca6c97393bdd8a09bc2039e3544dd02828f790bb3dcbd8fded52156d2e278a",
  "measuredOn": "/avatar/Sendagaya_Shibu_webp.vrm",
  "producedBy": "8f724ea",
  "faceBox": {
    "min": [
      -0.1067,
      1.3544,
      -0.1066
    ],
    "max": [
      0.1072,
      1.5865,
      0.0402
    ]
  },
  "handSkinPastTip": 0.0208,
  "restCrownY": 1.6158,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.6374,
        "right": 0.504
      },
      "skinTop": 1.502,
      "hipsLow": 0.852,
      "faceRatio": 1.499,
      "faceRatioAt": 9.45,
      "endSink": 0.0374,
      "hipsDrift": 0.0148,
      "endWrist": 0.8173
    },
    "modelPose": {
      "reach": {
        "left": 0.3657,
        "right": 0.34
      },
      "skinTop": 1.3366,
      "hipsLow": 0.8898,
      "faceRatio": 9.9997,
      "faceRatioAt": 3.88,
      "endSink": 0.0086,
      "hipsDrift": 0.0269,
      "endWrist": 0.862
    },
    "spin": {
      "reach": {
        "left": 0.705,
        "right": 0.5512
      },
      "skinTop": 1.5648,
      "hipsLow": 0.8598,
      "faceRatio": 4.7522,
      "faceRatioAt": 2.43,
      "endSink": 0,
      "hipsDrift": 0.0132,
      "endWrist": 0.8611
    },
    "squat": {
      "reach": {
        "left": 0.6562,
        "right": 0.6429
      },
      "skinTop": 1.4137,
      "hipsLow": 0.6837,
      "faceRatio": 1.6797,
      "faceRatioAt": 6.12,
      "endSink": 0,
      "hipsDrift": 0.0106,
      "endWrist": 0.8575
    },
    "akimbo": {
      "reach": {
        "left": 0.2897,
        "right": 0.3112
      },
      "skinTop": 1.0399,
      "hipsLow": 0.9133,
      "faceRatio": 16.129,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8648
    },
    "playFingers": {
      "reach": {
        "left": 0.2758,
        "right": 0.2771
      },
      "skinTop": 1.0864,
      "hipsLow": 0.9135,
      "faceRatio": 19.4966,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8648
    },
    "scratchHead": {
      "reach": {
        "left": 0.4019,
        "right": 0.5442
      },
      "skinTop": 1.6454,
      "hipsLow": 0.909,
      "faceRatio": 0.7622,
      "faceRatioAt": 4.3,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8648
    },
    "idleLoop": {
      "reach": {
        "left": 0.3979,
        "right": 0.1002
      },
      "skinTop": 0.8639,
      "hipsLow": 0.9075,
      "faceRatio": 31.6484,
      "faceRatioAt": 1.54,
      "endSink": 0.0015,
      "hipsDrift": 0.1576,
      "endWrist": 0.8502
    },
    "stretch": {
      "reach": {
        "left": 0.3435,
        "right": 0.5724
      },
      "skinTop": 1.8739,
      "hipsLow": 0.914,
      "faceRatio": 2.4638,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8648
    },
    "dance": {
      "reach": {
        "left": 0.7384,
        "right": 0.5226
      },
      "skinTop": 1.5579,
      "hipsLow": 0.7795,
      "faceRatio": 0.1897,
      "faceRatioAt": 8.23,
      "endSink": 0.0487,
      "hipsDrift": 0.1452,
      "endWrist": 1.2392
    }
  }
}
