// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/Sendagaya_Shino_webp.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown. Regenerate:
//   npx tsx scripts/measure-motions.ts public/avatar/Sendagaya_Shino_webp.vrm --write src/components/chat/clearance/vroid-sendagaya-shino.measured.gen.ts --family=vroid-sendagaya-shino
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-sendagaya-shino",
  "rigSha": "ba2bf7326d1807b0d352a4b81a68f2024ca94c449224448bdb94c48d97912965",
  "measuredOn": "/avatar/Sendagaya_Shino_webp.vrm",
  "producedBy": "8f724ea",
  "faceBox": {
    "min": [
      -0.1084,
      1.3832,
      -0.108
    ],
    "max": [
      0.109,
      1.6164,
      0.0405
    ]
  },
  "handSkinPastTip": 0.0208,
  "restCrownY": 1.6451,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.6383,
        "right": 0.5027
      },
      "skinTop": 1.5283,
      "hipsLow": 0.8757,
      "faceRatio": 1.4709,
      "faceRatioAt": 9.45,
      "endSink": 0.0384,
      "hipsDrift": 0.0152,
      "endWrist": 0.8436
    },
    "modelPose": {
      "reach": {
        "left": 0.3686,
        "right": 0.3411
      },
      "skinTop": 1.3635,
      "hipsLow": 0.9146,
      "faceRatio": 9.8183,
      "faceRatioAt": 3.88,
      "endSink": 0.0088,
      "hipsDrift": 0.0277,
      "endWrist": 0.8891
    },
    "spin": {
      "reach": {
        "left": 0.7069,
        "right": 0.5497
      },
      "skinTop": 1.5922,
      "hipsLow": 0.8837,
      "faceRatio": 4.7622,
      "faceRatioAt": 2.43,
      "endSink": 0,
      "hipsDrift": 0.0136,
      "endWrist": 0.8886
    },
    "squat": {
      "reach": {
        "left": 0.6564,
        "right": 0.643
      },
      "skinTop": 1.4414,
      "hipsLow": 0.7027,
      "faceRatio": 1.6734,
      "faceRatioAt": 6.12,
      "endSink": 0,
      "hipsDrift": 0.0109,
      "endWrist": 0.8851
    },
    "akimbo": {
      "reach": {
        "left": 0.2895,
        "right": 0.3123
      },
      "skinTop": 1.0674,
      "hipsLow": 0.9387,
      "faceRatio": 16.0767,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8923
    },
    "playFingers": {
      "reach": {
        "left": 0.2758,
        "right": 0.2771
      },
      "skinTop": 1.114,
      "hipsLow": 0.9389,
      "faceRatio": 19.3184,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8923
    },
    "scratchHead": {
      "reach": {
        "left": 0.4031,
        "right": 0.5435
      },
      "skinTop": 1.6727,
      "hipsLow": 0.9343,
      "faceRatio": 0.7263,
      "faceRatioAt": 4.3,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8923
    },
    "idleLoop": {
      "reach": {
        "left": 0.4027,
        "right": 0.0966
      },
      "skinTop": 0.8913,
      "hipsLow": 0.9327,
      "faceRatio": 31.5095,
      "faceRatioAt": 1.54,
      "endSink": 0.0016,
      "hipsDrift": 0.162,
      "endWrist": 0.8776
    },
    "stretch": {
      "reach": {
        "left": 0.3437,
        "right": 0.5721
      },
      "skinTop": 1.9017,
      "hipsLow": 0.9394,
      "faceRatio": 2.4381,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.8923
    },
    "dance": {
      "reach": {
        "left": 0.7438,
        "right": 0.5326
      },
      "skinTop": 1.5862,
      "hipsLow": 0.8011,
      "faceRatio": 0.1938,
      "faceRatioAt": 8.23,
      "endSink": 0.0501,
      "hipsDrift": 0.1492,
      "endWrist": 1.2652
    }
  }
}
