// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/Vivi_webp.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown. Regenerate:
//   npx tsx scripts/measure-motions.ts public/avatar/Vivi_webp.vrm --write src/components/chat/clearance/vroid-vivi.measured.gen.ts --family=vroid-vivi
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-vivi",
  "rigSha": "4e782ba7af36e3e8059ce4b3fecd6ac2d4fc1ba782846fd104fb8e9a3f9e9daa",
  "measuredOn": "/avatar/Vivi_webp.vrm",
  "producedBy": "8f724ea",
  "faceBox": {
    "min": [
      -0.0967,
      1.1637,
      -0.0992
    ],
    "max": [
      0.0972,
      1.3757,
      0.035
    ]
  },
  "handSkinPastTip": 0.0175,
  "restCrownY": 1.4122,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.5353,
        "right": 0.4209
      },
      "skinTop": 1.2817,
      "hipsLow": 0.7272,
      "faceRatio": 1.3498,
      "faceRatioAt": 9.45,
      "endSink": 0.0319,
      "hipsDrift": 0.0126,
      "endWrist": 0.708
    },
    "modelPose": {
      "reach": {
        "left": 0.3368,
        "right": 0.3153
      },
      "skinTop": 1.1432,
      "hipsLow": 0.7595,
      "faceRatio": 8.6144,
      "faceRatioAt": 3.88,
      "endSink": 0.0073,
      "hipsDrift": 0.023,
      "endWrist": 0.7458
    },
    "spin": {
      "reach": {
        "left": 0.5936,
        "right": 0.4631
      },
      "skinTop": 1.336,
      "hipsLow": 0.7339,
      "faceRatio": 4.2943,
      "faceRatioAt": 2.43,
      "endSink": 0,
      "hipsDrift": 0.0113,
      "endWrist": 0.7452
    },
    "squat": {
      "reach": {
        "left": 0.5531,
        "right": 0.5406
      },
      "skinTop": 1.2117,
      "hipsLow": 0.5836,
      "faceRatio": 1.6052,
      "faceRatioAt": 6.12,
      "endSink": 0,
      "hipsDrift": 0.009,
      "endWrist": 0.7422
    },
    "akimbo": {
      "reach": {
        "left": 0.2443,
        "right": 0.2912
      },
      "skinTop": 0.8996,
      "hipsLow": 0.7795,
      "faceRatio": 14.4345,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0006,
      "endWrist": 0.7486
    },
    "playFingers": {
      "reach": {
        "left": 0.2453,
        "right": 0.2452
      },
      "skinTop": 0.9373,
      "hipsLow": 0.7797,
      "faceRatio": 16.9452,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0006,
      "endWrist": 0.7486
    },
    "scratchHead": {
      "reach": {
        "left": 0.3688,
        "right": 0.4557
      },
      "skinTop": 1.4041,
      "hipsLow": 0.7759,
      "faceRatio": 0.5504,
      "faceRatioAt": 4.3,
      "endSink": 0,
      "hipsDrift": 0.0006,
      "endWrist": 0.7486
    },
    "idleLoop": {
      "reach": {
        "left": 0.3635,
        "right": 0.1095
      },
      "skinTop": 0.7497,
      "hipsLow": 0.7746,
      "faceRatio": 27.9947,
      "faceRatioAt": 1.54,
      "endSink": 0.0013,
      "hipsDrift": 0.1345,
      "endWrist": 0.7361
    },
    "stretch": {
      "reach": {
        "left": 0.3081,
        "right": 0.4815
      },
      "skinTop": 1.6024,
      "hipsLow": 0.7801,
      "faceRatio": 2.096,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0006,
      "endWrist": 0.7486
    },
    "dance": {
      "reach": {
        "left": 0.6212,
        "right": 0.4446
      },
      "skinTop": 1.3296,
      "hipsLow": 0.6653,
      "faceRatio": 0.2652,
      "faceRatioAt": 8.23,
      "endSink": 0.0416,
      "hipsDrift": 0.1239,
      "endWrist": 1.0622
    }
  }
}
