// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/mika-milfy-12.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/avatar/springsim.ts public/avatar/mika-milfy-12.vrm --clearance=src/components/chat/clearance/vroid-sample-b.simulated.gen.ts --family=vroid-sample-b
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-sample-b",
  "rigSha": "e2aad79ec6667a5529934359339a6a08a29f73fe8a51f5cc6d4d702e137c1b45",
  "simulatedOn": "/avatar/mika-milfy-12.vrm",
  "producedBy": "d89982b",
  "restCrownY": 1.5757,
  "restCrownScreen": {
    "waistUp": 1.5786,
    "column": 1.5881
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "playFingers": {
        "column": 0.02
      },
      "scratchHead": {
        "column": 0.02
      },
      "dance": {
        "waistUp": -0.07,
        "column": 0.14
      },
      "groove": {
        "waistUp": -0.13,
        "column": 0.08
      },
      "macarena": {
        "waistUp": -0.22,
        "column": 0.03
      },
      "catwalk": {
        "column": 0.04
      },
      "jumpAround": {
        "waistUp": 0.13,
        "column": 0.38
      },
      "cheer": {
        "waistUp": -0.07,
        "column": 0.19
      },
      "shyPose": {
        "column": 0.03
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.5833,
      "crownT": 0.5,
      "crownScreen": {
        "waistUp": 1.5837,
        "column": 1.593
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 39.5,
      "jumpDeg": 2.5,
      "skirtDepthMm": -19
    },
    "catwalk": {
      "crownY": 1.5723,
      "crownT": 11.53,
      "crownScreen": {
        "waistUp": 1.5727,
        "column": 1.5881
      },
      "coatDepthMm": 38.1,
      "bodyDepthMm": 50,
      "jumpDeg": 18.7,
      "skirtDepthMm": 20.9
    },
    "cheer": {
      "crownY": 1.7313,
      "crownT": 1.97,
      "crownScreen": {
        "waistUp": 1.7712,
        "column": 1.7747
      },
      "coatDepthMm": 112.8,
      "bodyDepthMm": 50,
      "jumpDeg": 50.6,
      "skirtDepthMm": 21.1
    },
    "dance": {
      "crownY": 1.6647,
      "crownT": 11.97,
      "crownScreen": {
        "waistUp": 1.7,
        "column": 1.7087
      },
      "coatDepthMm": 37.5,
      "bodyDepthMm": 50,
      "jumpDeg": 21.7,
      "skirtDepthMm": 18.3
    },
    "groove": {
      "crownY": 1.5896,
      "crownT": 5.57,
      "crownScreen": {
        "waistUp": 1.6054,
        "column": 1.6098
      },
      "coatDepthMm": 18.8,
      "bodyDepthMm": 49.8,
      "jumpDeg": 22,
      "skirtDepthMm": 49.8
    },
    "idleLoop": {
      "crownY": 1.5774,
      "crownT": 1.2,
      "crownScreen": {
        "waistUp": 1.582,
        "column": 1.5965
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 4.8,
      "jumpDeg": 0.3,
      "skirtDepthMm": -18.8
    },
    "jumpAround": {
      "crownY": 1.8629,
      "crownT": 3.67,
      "crownScreen": {
        "waistUp": 1.8969,
        "column": 1.9006
      },
      "coatDepthMm": 47.1,
      "bodyDepthMm": 50,
      "jumpDeg": 36.7,
      "skirtDepthMm": -18.6
    },
    "macarena": {
      "crownY": 1.5884,
      "crownT": 8.03,
      "crownScreen": {
        "waistUp": 1.605,
        "column": 1.607
      },
      "coatDepthMm": 40.1,
      "bodyDepthMm": 49.9,
      "jumpDeg": 19.8,
      "skirtDepthMm": 19.2
    },
    "modelPose": {
      "crownY": 1.5754,
      "crownT": 0.5,
      "crownScreen": {
        "waistUp": 1.5728,
        "column": 1.577
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 15.9,
      "jumpDeg": 5,
      "skirtDepthMm": -19
    },
    "peaceSign": {
      "crownY": 1.5463,
      "crownT": 0.77,
      "crownScreen": {
        "waistUp": 1.5476,
        "column": 1.5578
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 4.5,
      "skirtDepthMm": -19
    },
    "playFingers": {
      "crownY": 1.5822,
      "crownT": 4.6,
      "crownScreen": {
        "waistUp": 1.5835,
        "column": 1.5928
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 4.8,
      "jumpDeg": 1.9,
      "skirtDepthMm": -19.2
    },
    "scratchHead": {
      "crownY": 1.583,
      "crownT": 5.83,
      "crownScreen": {
        "waistUp": 1.5835,
        "column": 1.5924
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 3.5,
      "skirtDepthMm": -19.2
    },
    "shyPose": {
      "crownY": 1.5692,
      "crownT": 7.9,
      "crownScreen": {
        "waistUp": 1.5719,
        "column": 1.5804
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 10.4,
      "skirtDepthMm": -14.8
    },
    "spin": {
      "crownY": 1.5886,
      "crownT": 6.83,
      "crownScreen": {
        "waistUp": 1.5958,
        "column": 1.6107
      },
      "coatDepthMm": 41.8,
      "bodyDepthMm": 4.8,
      "jumpDeg": 12.4,
      "skirtDepthMm": -19
    },
    "squat": {
      "crownY": 1.5928,
      "crownT": 8.2,
      "crownScreen": {
        "waistUp": 1.5918,
        "column": 1.5944
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 4.8,
      "jumpDeg": 12.7,
      "skirtDepthMm": -19
    },
    "stretch": {
      "crownY": 1.7992,
      "crownT": 1.8,
      "crownScreen": {
        "waistUp": 1.8081,
        "column": 1.8213
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 4.8,
      "jumpDeg": 3.5,
      "skirtDepthMm": -19.1
    }
  }
}
