// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/AvatarSample_A_webp.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown. Regenerate:
//   npx tsx scripts/measure-motions.ts public/avatar/AvatarSample_A_webp.vrm --write src/components/chat/clearance/vroid-sample-a.measured.gen.ts --family=vroid-sample-a
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-sample-a",
  "rigSha": "e1a17d2f3e50d140cd31acb423888e886017e4deb0c3d788a489cb4b4919b6a9",
  "measuredOn": "/avatar/AvatarSample_A_webp.vrm",
  "producedBy": "8f724ea",
  "faceBox": {
    "min": [
      -0.0954,
      1.3178,
      -0.1169
    ],
    "max": [
      0.0954,
      1.5419,
      0.0336
    ]
  },
  "handSkinPastTip": 0.0182,
  "restCrownY": 1.5582,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.6238,
        "right": 0.4841
      },
      "skinTop": 1.4629,
      "hipsLow": 0.8393,
      "faceRatio": 1.9106,
      "faceRatioAt": 9.45,
      "endSink": 0.0368,
      "hipsDrift": 0.0145,
      "endWrist": 0.7534
    },
    "modelPose": {
      "reach": {
        "left": 0.4223,
        "right": 0.3826
      },
      "skinTop": 1.2917,
      "hipsLow": 0.8766,
      "faceRatio": 11.1866,
      "faceRatioAt": 3.87,
      "endSink": 0.0084,
      "hipsDrift": 0.0265,
      "endWrist": 0.8015
    },
    "spin": {
      "reach": {
        "left": 0.7,
        "right": 0.5466
      },
      "skinTop": 1.531,
      "hipsLow": 0.847,
      "faceRatio": 5.6681,
      "faceRatioAt": 2.45,
      "endSink": 0,
      "hipsDrift": 0.013,
      "endWrist": 0.8002
    },
    "squat": {
      "reach": {
        "left": 0.6538,
        "right": 0.6405
      },
      "skinTop": 1.3856,
      "hipsLow": 0.6735,
      "faceRatio": 2.6451,
      "faceRatioAt": 6.08,
      "endSink": 0,
      "hipsDrift": 0.0104,
      "endWrist": 0.7974
    },
    "akimbo": {
      "reach": {
        "left": 0.3208,
        "right": 0.4058
      },
      "skinTop": 0.9871,
      "hipsLow": 0.8996,
      "faceRatio": 18.3038,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.7997
    },
    "playFingers": {
      "reach": {
        "left": 0.3208,
        "right": 0.3221
      },
      "skinTop": 1.032,
      "hipsLow": 0.8999,
      "faceRatio": 21.9298,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.7997
    },
    "scratchHead": {
      "reach": {
        "left": 0.4206,
        "right": 0.532
      },
      "skinTop": 1.6097,
      "hipsLow": 0.8954,
      "faceRatio": 1.243,
      "faceRatioAt": 4.45,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.7997
    },
    "idleLoop": {
      "reach": {
        "left": 0.4997,
        "right": 0.1963
      },
      "skinTop": 0.8001,
      "hipsLow": 0.8939,
      "faceRatio": 35.8583,
      "faceRatioAt": 1.21,
      "endSink": 0.0015,
      "hipsDrift": 0.1552,
      "endWrist": 0.7866
    },
    "stretch": {
      "reach": {
        "left": 0.3515,
        "right": 0.5678
      },
      "skinTop": 1.8561,
      "hipsLow": 0.9004,
      "faceRatio": 2.1557,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.7997
    },
    "dance": {
      "reach": {
        "left": 0.7226,
        "right": 0.7108
      },
      "skinTop": 1.5263,
      "hipsLow": 0.7678,
      "faceRatio": 0.2062,
      "faceRatioAt": 8.22,
      "endSink": 0.048,
      "hipsDrift": 0.143,
      "endWrist": 1.2195
    }
  }
}
