// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/HairSample_Male_webp.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown. Regenerate:
//   npx tsx scripts/measure-motions.ts public/avatar/HairSample_Male_webp.vrm --write src/components/chat/clearance/vroid-hair-male.measured.gen.ts --family=vroid-hair-male
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-hair-male",
  "rigSha": "8d88e224dc7943803f54f2e84dae2f1383426089b5369a292b4a94423a5f9e49",
  "measuredOn": "/avatar/HairSample_Male_webp.vrm",
  "producedBy": "8f724ea",
  "faceBox": {
    "min": [
      -0.1114,
      1.4962,
      -0.1277
    ],
    "max": [
      0.1124,
      1.7405,
      0.0218
    ]
  },
  "handSkinPastTip": 0.0231,
  "restCrownY": 1.8067,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.7255,
        "right": 0.5734
      },
      "skinTop": 1.6778,
      "hipsLow": 0.9443,
      "faceRatio": 1.3343,
      "faceRatioAt": 9.45,
      "endSink": 0.0414,
      "hipsDrift": 0.0164,
      "endWrist": 0.9099
    },
    "modelPose": {
      "reach": {
        "left": 0.4178,
        "right": 0.4282
      },
      "skinTop": 1.492,
      "hipsLow": 0.9862,
      "faceRatio": 11.5634,
      "faceRatioAt": 3.88,
      "endSink": 0.0095,
      "hipsDrift": 0.0299,
      "endWrist": 0.951
    },
    "spin": {
      "reach": {
        "left": 0.7986,
        "right": 0.6206
      },
      "skinTop": 1.7357,
      "hipsLow": 0.9529,
      "faceRatio": 4.2297,
      "faceRatioAt": 2.43,
      "endSink": 0,
      "hipsDrift": 0.0146,
      "endWrist": 0.9518
    },
    "squat": {
      "reach": {
        "left": 0.7407,
        "right": 0.7285
      },
      "skinTop": 1.5716,
      "hipsLow": 0.7577,
      "faceRatio": 1.0848,
      "faceRatioAt": 6.08,
      "endSink": 0,
      "hipsDrift": 0.0117,
      "endWrist": 0.945
    },
    "akimbo": {
      "reach": {
        "left": 0.342,
        "right": 0.427
      },
      "skinTop": 1.1459,
      "hipsLow": 1.0122,
      "faceRatio": 17.2352,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.963
    },
    "playFingers": {
      "reach": {
        "left": 0.3496,
        "right": 0.3513
      },
      "skinTop": 1.2073,
      "hipsLow": 1.0125,
      "faceRatio": 20.7951,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.963
    },
    "scratchHead": {
      "reach": {
        "left": 0.5014,
        "right": 0.6218
      },
      "skinTop": 1.8374,
      "hipsLow": 1.0075,
      "faceRatio": 0.9514,
      "faceRatioAt": 4.3,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.963
    },
    "idleLoop": {
      "reach": {
        "left": 0.4743,
        "right": 0.1446
      },
      "skinTop": 0.9576,
      "hipsLow": 1.0058,
      "faceRatio": 34.5175,
      "faceRatioAt": 1.54,
      "endSink": 0.0017,
      "hipsDrift": 0.1747,
      "endWrist": 0.944
    },
    "stretch": {
      "reach": {
        "left": 0.4114,
        "right": 0.6564
      },
      "skinTop": 2.0819,
      "hipsLow": 1.013,
      "faceRatio": 2.3102,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0007,
      "endWrist": 0.963
    },
    "dance": {
      "reach": {
        "left": 0.8373,
        "right": 0.5834
      },
      "skinTop": 1.7294,
      "hipsLow": 0.8639,
      "faceRatio": 0.1898,
      "faceRatioAt": 0.6,
      "endSink": 0.054,
      "hipsDrift": 0.1609,
      "endWrist": 1.3897
    }
  }
}
