// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/mika-pink.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown. Regenerate:
//   npx tsx scripts/measure-motions.ts public/avatar/mika-pink.vrm --write src/components/chat/clearance/vroid-sample-b.measured.gen.ts --family=vroid-sample-b
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-sample-b",
  "rigSha": "e2aad79ec6667a5529934359339a6a08a29f73fe8a51f5cc6d4d702e137c1b45",
  "measuredOn": "/avatar/mika-pink.vrm",
  "producedBy": "571e711",
  "faceBox": {
    "min": [
      -0.0917,
      1.2873,
      -0.1126
    ],
    "max": [
      0.0918,
      1.5034,
      0.0326
    ]
  },
  "handSkinPastTip": 0.018,
  "restCrownY": 1.582,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.6088,
        "right": 0.4735
      },
      "skinTop": 1.4268,
      "hipsLow": 0.8225,
      "faceRatio": 1.9245,
      "faceRatioAt": 9.45,
      "endSink": 0.0361,
      "hipsDrift": 0.0142,
      "endWrist": 0.7357
    },
    "modelPose": {
      "reach": {
        "left": 0.3619,
        "right": 0.3647
      },
      "skinTop": 1.2604,
      "hipsLow": 0.859,
      "faceRatio": 11.3843,
      "faceRatioAt": 3.87,
      "endSink": 0.0083,
      "hipsDrift": 0.026,
      "endWrist": 0.7826
    },
    "spin": {
      "reach": {
        "left": 0.683,
        "right": 0.5329
      },
      "skinTop": 1.4933,
      "hipsLow": 0.83,
      "faceRatio": 5.7712,
      "faceRatioAt": 2.45,
      "endSink": 0,
      "hipsDrift": 0.0127,
      "endWrist": 0.7815
    },
    "squat": {
      "reach": {
        "left": 0.6379,
        "right": 0.6245
      },
      "skinTop": 1.3508,
      "hipsLow": 0.66,
      "faceRatio": 2.7028,
      "faceRatioAt": 6.12,
      "endSink": 0,
      "hipsDrift": 0.0102,
      "endWrist": 0.7787
    },
    "akimbo": {
      "reach": {
        "left": 0.2793,
        "right": 0.3507
      },
      "skinTop": 0.964,
      "hipsLow": 0.8817,
      "faceRatio": 18.7142,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0006,
      "endWrist": 0.7811
    },
    "playFingers": {
      "reach": {
        "left": 0.2836,
        "right": 0.2842
      },
      "skinTop": 1.0079,
      "hipsLow": 0.8819,
      "faceRatio": 22.3535,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0006,
      "endWrist": 0.7811
    },
    "scratchHead": {
      "reach": {
        "left": 0.426,
        "right": 0.5196
      },
      "skinTop": 1.57,
      "hipsLow": 0.8776,
      "faceRatio": 1.2173,
      "faceRatioAt": 4.43,
      "endSink": 0,
      "hipsDrift": 0.0006,
      "endWrist": 0.7811
    },
    "idleLoop": {
      "reach": {
        "left": 0.4364,
        "right": 0.1449
      },
      "skinTop": 0.7818,
      "hipsLow": 0.8761,
      "faceRatio": 36.6637,
      "faceRatioAt": 1.21,
      "endSink": 0.0015,
      "hipsDrift": 0.1521,
      "endWrist": 0.7682
    },
    "stretch": {
      "reach": {
        "left": 0.3602,
        "right": 0.5533
      },
      "skinTop": 1.8091,
      "hipsLow": 0.8824,
      "faceRatio": 2.2361,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0006,
      "endWrist": 0.7811
    },
    "dance": {
      "reach": {
        "left": 0.7068,
        "right": 0.6476
      },
      "skinTop": 1.4886,
      "hipsLow": 0.7525,
      "faceRatio": 0.1975,
      "faceRatioAt": 8.22,
      "endSink": 0.0471,
      "hipsDrift": 0.1402,
      "endWrist": 1.1877
    }
  }
}
