// GENERATED by scripts/measure-motions.ts --write — do not edit by hand.
// Body /avatar/Vivi_webp-2.vrm under every clip in AVATAR_MOTIONS, by forward kinematics on
// three-vrm's VRMHumanoid (rigProbe.ts): the worst frame of each clip, and what the mesh
// says about the face, the finger skin and the resting crown.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/measure-motions.ts public/avatar/Vivi_webp-2.vrm --write src/components/chat/clearance/vroid-vivi.measured.gen.ts --family=vroid-vivi
import type { ClearanceMeasured } from '../clearance'

export const MEASURED: ClearanceMeasured = {
  "family": "vroid-vivi",
  "rigSha": "9f6ed8918852edc3dfdd431907e9dfaef38ca72c33f1c60b8ac944ca2f1de6d0",
  "measuredOn": "/avatar/Vivi_webp-2.vrm",
  "producedBy": "953cf0b",
  "faceBox": {
    "min": [
      -0.1083,
      1.3037,
      -0.1111
    ],
    "max": [
      0.1089,
      1.5412,
      0.0392
    ]
  },
  "handSkinPastTip": 0.0196,
  "restCrownY": 1.582,
  "clips": {
    "peaceSign": {
      "reach": {
        "left": 0.5997,
        "right": 0.4716
      },
      "skinTop": 1.4344,
      "hipsLow": 0.8147,
      "faceRatio": 1.3498,
      "faceRatioAt": 9.45,
      "endSink": 0.0357,
      "hipsDrift": 0.0141,
      "endWrist": 0.7931
    },
    "modelPose": {
      "reach": {
        "left": 0.3773,
        "right": 0.3532
      },
      "skinTop": 1.2792,
      "hipsLow": 0.8508,
      "faceRatio": 8.6144,
      "faceRatioAt": 3.88,
      "endSink": 0.0082,
      "hipsDrift": 0.0258,
      "endWrist": 0.8355
    },
    "spin": {
      "reach": {
        "left": 0.665,
        "right": 0.5187
      },
      "skinTop": 1.4952,
      "hipsLow": 0.8221,
      "faceRatio": 4.2943,
      "faceRatioAt": 2.43,
      "endSink": 0,
      "hipsDrift": 0.0126,
      "endWrist": 0.8348
    },
    "squat": {
      "reach": {
        "left": 0.6196,
        "right": 0.6056
      },
      "skinTop": 1.3559,
      "hipsLow": 0.6537,
      "faceRatio": 1.6052,
      "faceRatioAt": 6.12,
      "endSink": 0,
      "hipsDrift": 0.0101,
      "endWrist": 0.8314
    },
    "akimbo": {
      "reach": {
        "left": 0.2736,
        "right": 0.3262
      },
      "skinTop": 1.0063,
      "hipsLow": 0.8732,
      "faceRatio": 14.4345,
      "faceRatioAt": 6.4,
      "endSink": 0,
      "hipsDrift": 0.0006,
      "endWrist": 0.8386
    },
    "playFingers": {
      "reach": {
        "left": 0.2748,
        "right": 0.2746
      },
      "skinTop": 1.0485,
      "hipsLow": 0.8735,
      "faceRatio": 16.9452,
      "faceRatioAt": 2.67,
      "endSink": 0,
      "hipsDrift": 0.0006,
      "endWrist": 0.8386
    },
    "scratchHead": {
      "reach": {
        "left": 0.4132,
        "right": 0.5105
      },
      "skinTop": 1.5715,
      "hipsLow": 0.8692,
      "faceRatio": 0.5504,
      "faceRatioAt": 4.3,
      "endSink": 0,
      "hipsDrift": 0.0006,
      "endWrist": 0.8386
    },
    "idleLoop": {
      "reach": {
        "left": 0.4072,
        "right": 0.1227
      },
      "skinTop": 0.8384,
      "hipsLow": 0.8677,
      "faceRatio": 27.9947,
      "faceRatioAt": 1.54,
      "endSink": 0.0015,
      "hipsDrift": 0.1507,
      "endWrist": 0.8246
    },
    "stretch": {
      "reach": {
        "left": 0.3451,
        "right": 0.5393
      },
      "skinTop": 1.7936,
      "hipsLow": 0.8739,
      "faceRatio": 2.096,
      "faceRatioAt": 1.87,
      "endSink": 0,
      "hipsDrift": 0.0006,
      "endWrist": 0.8386
    },
    "dance": {
      "reach": {
        "left": 0.6959,
        "right": 0.4981
      },
      "skinTop": 1.488,
      "hipsLow": 0.7453,
      "faceRatio": 0.2652,
      "faceRatioAt": 8.23,
      "endSink": 0.0466,
      "hipsDrift": 0.1388,
      "endWrist": 1.1899
    }
  }
}
