// GENERATED by scripts/avatar/springsim.ts --clearance — do not edit by hand.
// Body /avatar/Vivi_webp-2.vrm through three-vrm's spring solver at 60 Hz, every clip in
// public/avatar/animations. crownY is the topmost drawn vertex at any frame, restCrownY the
// same in bind pose, crownScreen/restCrownScreen those two through each frame's camera
// (framings, recorded here as they were); depths are the worst frame.
// Regenerate from a checkout of the vtuber-kit repo:
//   npx tsx scripts/avatar/springsim.ts public/avatar/Vivi_webp-2.vrm --clearance=src/components/chat/clearance/vroid-vivi.simulated.gen.ts --family=vroid-vivi
import type { ClearanceSimulated } from '../clearance'

export const SIMULATED: ClearanceSimulated = {
  "family": "vroid-vivi",
  "rigSha": "9f6ed8918852edc3dfdd431907e9dfaef38ca72c33f1c60b8ac944ca2f1de6d0",
  "simulatedOn": "/avatar/Vivi_webp-2.vrm",
  "producedBy": "d89982b",
  "restCrownY": 1.582,
  "restCrownScreen": {
    "waistUp": 1.588,
    "column": 1.6008
  },
  "framings": {
    "fov": 27,
    "tilt": 0.1,
    "frames": {
      "waistUp": {
        "distance": 2.3,
        "lookAtY": 1.32
      },
      "column": {
        "distance": 2.441,
        "lookAtY": 1.016
      }
    },
    "pans": {
      "spin": {
        "column": 0.02
      },
      "squat": {
        "column": 0.01
      },
      "akimbo": {
        "column": 0.01
      },
      "playFingers": {
        "column": 0.01
      },
      "scratchHead": {
        "column": 0.01
      },
      "idleLoop": {
        "column": 0.01
      },
      "dance": {
        "waistUp": -0.09,
        "column": 0.11
      },
      "groove": {
        "waistUp": -0.16,
        "column": 0.02
      },
      "macarena": {
        "waistUp": -0.23,
        "column": 0.02
      },
      "jumpAround": {
        "waistUp": 0.05,
        "column": 0.3
      },
      "cheer": {
        "waistUp": -0.1,
        "column": 0.17
      }
    }
  },
  "clips": {
    "akimbo": {
      "crownY": 1.5873,
      "crownT": 10.13,
      "crownScreen": {
        "waistUp": 1.593,
        "column": 1.6052
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 2.5,
      "skirtDepthMm": 0
    },
    "catwalk": {
      "crownY": 1.5797,
      "crownT": 2.6,
      "crownScreen": {
        "waistUp": 1.5859,
        "column": 1.6013
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 19.1,
      "skirtDepthMm": 0
    },
    "cheer": {
      "crownY": 1.7201,
      "crownT": 1.97,
      "crownScreen": {
        "waistUp": 1.7671,
        "column": 1.7684
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 161.1,
      "skirtDepthMm": 0
    },
    "dance": {
      "crownY": 1.6596,
      "crownT": 11.93,
      "crownScreen": {
        "waistUp": 1.6889,
        "column": 1.6965
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 37.5,
      "skirtDepthMm": 0
    },
    "groove": {
      "crownY": 1.5907,
      "crownT": 5.53,
      "crownScreen": {
        "waistUp": 1.6099,
        "column": 1.6186
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 42.8,
      "skirtDepthMm": 0
    },
    "idleLoop": {
      "crownY": 1.5835,
      "crownT": 6.23,
      "crownScreen": {
        "waistUp": 1.5915,
        "column": 1.6074
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 22.4,
      "jumpDeg": 0.4,
      "skirtDepthMm": 0
    },
    "jumpAround": {
      "crownY": 1.8626,
      "crownT": 2.67,
      "crownScreen": {
        "waistUp": 1.8974,
        "column": 1.9002
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 146,
      "skirtDepthMm": 0
    },
    "macarena": {
      "crownY": 1.5847,
      "crownT": 8.03,
      "crownScreen": {
        "waistUp": 1.6116,
        "column": 1.6139
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 15.6,
      "skirtDepthMm": 0
    },
    "modelPose": {
      "crownY": 1.5744,
      "crownT": 0.43,
      "crownScreen": {
        "waistUp": 1.5762,
        "column": 1.5872
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 2.8,
      "skirtDepthMm": 0
    },
    "peaceSign": {
      "crownY": 1.5465,
      "crownT": 0.73,
      "crownScreen": {
        "waistUp": 1.553,
        "column": 1.57
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 4.4,
      "skirtDepthMm": 0
    },
    "playFingers": {
      "crownY": 1.5865,
      "crownT": 0.03,
      "crownScreen": {
        "waistUp": 1.593,
        "column": 1.606
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.7,
      "jumpDeg": 2.9,
      "skirtDepthMm": 0
    },
    "scratchHead": {
      "crownY": 1.5868,
      "crownT": 0.03,
      "crownScreen": {
        "waistUp": 1.5935,
        "column": 1.6064
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 27.4,
      "skirtDepthMm": 0
    },
    "shyPose": {
      "crownY": 1.5693,
      "crownT": 7.9,
      "crownScreen": {
        "waistUp": 1.5733,
        "column": 1.592
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 10,
      "skirtDepthMm": 0
    },
    "spin": {
      "crownY": 1.5865,
      "crownT": 2,
      "crownScreen": {
        "waistUp": 1.5967,
        "column": 1.6172
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 22.1,
      "skirtDepthMm": 0
    },
    "squat": {
      "crownY": 1.6043,
      "crownT": 8.27,
      "crownScreen": {
        "waistUp": 1.6045,
        "column": 1.6078
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 50,
      "jumpDeg": 7.5,
      "skirtDepthMm": 0
    },
    "stretch": {
      "crownY": 1.7839,
      "crownT": 1.7,
      "crownScreen": {
        "waistUp": 1.7908,
        "column": 1.8022
      },
      "coatDepthMm": 0,
      "bodyDepthMm": 49.9,
      "jumpDeg": 6.5,
      "skirtDepthMm": 0
    }
  }
}
